cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -46,7 +46,7 @@ function gy  {            geth attach --exec eth.syncing   "http://$cgth:8545" 2
 function gi  { echo $@|sed 's%.*highestBlock: *\([0-9]*\).*%\1%'; }                                                                                           # get highest geth block
 function gc  { echo $@|sed 's%.*currentBlock: *\([0-9]*\).*%\1%'; }                                                                                           # get current geth block
 function gb  { g0=$(fs0 'mported new' 0 geth|wc -l);ok=OK;[[ $g0 -eq $(fs7 .*sgs: $p5 1) ]] && ok=BK; }                                                       # imported new chain segments & OK/BK
-function gh0 { [[ -f $p5 ]] || return;tail -n${1:-$hors} $p5;[[ $1 ]] && return;gl0;echo -e "$m\n";sso GETH $n0;cpe; }                                        # geth historic report
+function gh0 { [[ -f $p5 ]] || return;tail -n${1:-$hors} $p5;[[ $1 ]] && return;gl0;nex "$m\n";sso GETH $n0;cpe; }                                        # geth historic report
 function gl0 {                                                                                                                                                # geth report
   dts;ok=OK;if [[ $(sst $n0 running) ]];then local e=$(gy);gb;gv;gq;m="$(dnn) sgs: $(printf '%4i' $g0)"
     if [[ $(echo $e|grep false) ]];then m="GETH $ok SYC $m";else m="GETH $ok NSY $m blocks: $(($(gi $e)-$(gc $e)))";fi                                        # OK SYC/NSY (dnn) sgs: 5 blocks: 8 (6)
@@ -64,9 +64,10 @@ function bw  { echo $((10*z1))                                                  
 function bf  { echo $((90*z3))                                                      ; }                                                                       # get numerator general errors
 function bi  { echo $((nd+zk*300+zz*20+zx))                                         ; }                                                                       # get delete day idx
 function bu  { echo $(((z5>400?$(bz)/z5:0)+(z2>300?$(bw)/z2:0)+(z4>999?$(bf)/z4:0))); }                                                                       # get restart idx
-function bk  { cat $p2 2>$s3|wc -l; }                                                                                                                         # get beacon line count
 function bv  { nu0 $(ss1 $n1 target-peers [0-9]); }                                                                                                           # get configured peers
 function bb  { l0=$(fs0 $bpid] 3600);bl1;bl2;[[ (1 -eq $(bl6 $hors) && $(bu) -ge 1) || (1 -eq $(bl6 5) && $(bu) -ge 5) ]] && ok=BK; }                         # set ok (OK/BK)
+function bbl { cat $p2 2>$s3|wc -l; }                                                                                                                         # get beacon line count
+function bml { cat $p3 2>$s3|wc -l; }                                                                                                                         # get medias line count
 function bfl { grep "BEAC.*$1"    ; }                                                                                                                         # filter beacon lines
 function bff { grep "BEAC.*$1" $p2; }                                                                                                                         # filter beacon log
 function bl0 { dts;ok=OK;if [[ $(sst $n1 running) ]];then bl3;nn=$(bv);bnn $(fs6 peers:);bb;blo;else m="BSRV NOT ON $dt";fi; }                                # beacon report
@@ -90,9 +91,9 @@ function blo {
 function bcc { if bct       ;then echo c;else echo _;fi; }                                                                                                    # get change configured peers char
 function bdc { if bht && bst;then echo d;else echo _;fi; }                                                                                                    # get delete beacon log day   char
 function bmi { zk=0;zz=0;zx=0;unset o;o[1]=0;unset k;k[0]=0;unset z;z[0]=0;unset x;x[0]=0;unset w;w[0]=0;unset c;c[0]=0;unset a;a[0]=0;bm6; }                 # ini err/cnt/avg penalty arrays
-function bm0 {                                                                                                                                                # bmedias report
+function bm0 {                                                                                                                                                # medias report
   [[ -f $p2 ]] || return
-  bmi;b4=0;b5=$(fs0 reduce|wc -l);dts;nn=$(bv);bnn $(fs6 peers:);bl2;[[ -f $p6 ]] && bm4;l3=$(tail -n$(($(bk)-o[1])) $p2 2>$s3|bfl);[[ $l3 ]] && bm1;bm2      # ini vars/arrays & add beacon lines
+  bmi;b4=0;b5=$(fs0 reduce|wc -l);dts;nn=$(bv);bnn $(fs6 peers:);bl2;[[ -f $p6 ]] && bm4;l3=$(tail -n$(($(bbl)-o[1])) $p2 2>$s3|bfl);[[ $l3 ]] && bm1;bm2     # ini vars/arrays & add beacon lines
   bo4;bm5 ${a[$nn]};b7="rm$(bdc)$(bcc)$(date +%w)_peers:"                                                                                                     # homologous/avg position & outputs
 }
 function bm1 {
@@ -135,7 +136,7 @@ function bms {
 }
 #    0   1          2     3    4 5 6 7 8 9 10 11   12 13 14 15 16 17 18 19   20 21 22 23 24 25 26 27   28 29 30 31 32 33 34 35   36 37 38 39 40 41 42 43
 # BEAC 682 2022-03-16 11:03 cnt: 4 7 0 0 0 10 10 mis: 20 20 20 20 20 20 20 mat: 14 45 30 30 30 30 30 mah: 94 68 40 40 40 40 40 dly: 79 09 50 50 50 50 50
-function bno { m="BEAC $(printf '%6i' $(bk)) $dt $(bnc 'cnt:' ' ') $(bnk 'mis:' ' ') $(bnz 'mat:' ' ') $(bnx 'mah:' ' ') $(bnw 'dly:' ' ')"; }
+function bno { m="BEAC $(printf '%6i' $(bbl)) $dt $(bnc 'cnt:' ' ') $(bnk 'mis:' ' ') $(bnz 'mat:' ' ') $(bnx 'mah:' ' ') $(bnw 'dly:' ' ')"; }
 function boi {
   unset v;read -a v <<< $(bff|tail -n1);local n=0;local t=${1:-00:00};[[ $t = 00:00 ]] && t=${v[4]};b6=0;l2=$(bff $t)                                         # set homologous lines
   while [[ ${b2:=0} -eq 0 && $n -lt 500 ]];do bo2 ${v[3]};((n+=1));v[3]=$(date -d "$n days ago $t" +%F);done                                                  # set homologous position
@@ -152,9 +153,9 @@ function bon { [[ -f $p2 ]] || return;nn=$(pt2 $1 $(bv));l2=$(bff 23:58);bo7 $nn
 function boa { local g=${1:-$bpri};echo "BO$(printf '%5i' $(bo7 $g|wc -l)) $(printf '%3i' $g)";bo7 $g;((g<bprf)) && boa $((g+bprs)); }                        # recursively show homologous nodes report
 function bh0 {
   [[ -f $p2 ]] || return;tail -n${1:-$hors} $p2;[[ $1 ]] && return                                                                                            # last beacon            report
-  boi;echo -e "BO$(printf '%5i' $(echo "$l2"|wc -l)) $(printf '%3i' $b2)$(printf '%91s')x5 x2  x1 x1";bo6                                                     # homologous             report
-  bl0;echo -e "BL$(printf '%9i' $(cat $p2|wc -l))\n$m";bm0                                                                                                    # current beacon         report
-  bmo;echo -e "BM$(printf '%9i' $(cat $p3 2>$s3|wc -l))$(printf '%46s')i20  i30  i40  i50  i60  i70  i80\n$m";sso BEAC $n1;sso VALI $n3;cpe                   # medias/services/system report
+  boi;nex "BO$(printf '%5i' $(echo "$l2"|wc -l)) $(printf '%3i' $b2)$(printf '%91s')x5 x2  x1 x1";bo6                                                         # homologous             report
+  bl0;nex "BL$(printf '%9i' $(bbl))\n$m";bm0                                                                                                                  # current beacon         report
+  bmo;nex "BM$(printf '%9i' $(bml))$(printf '%46s')i20  i30  i40  i50  i60  i70  i80\n$m";sso BEAC $n1;sso VALI $n3;cpe                                       # medias/services/system report
 }
 function brb { if srt;then echo RB;else echo $1;fi; }                                                                                                         # get reboot/other tag
 function bro { dts;bb;bnn $(fs6 peers:);[[ -f $p2 ]] && echo "$(printf 'R%03i' $1) ${2:-$ok} $(printf '%3i' $(bu)) $(dnn)" >> $p2; }                          # log restart info
@@ -188,7 +189,7 @@ function b1r {                                                                  
   fi;done;rm -f $e
 }
 function brh { head -n${1:-0} ${p2}r; }                                                                                                                       # new beacon head lines
-function brl {                                                                                                                                                # recalculate beacon/bmedias logs
+function brl {                                                                                                                                                # recalculate beacon/medias logs
   [[ -f $p2 ]] || return;rm -f ${p2}r
   unset v;while read -a v;do ok=${v[1]};dts ${v[3]}\ ${v[4]};nn=${v[5]:4:2};nr=${v[6]}                                                                        # uncalculated vars
     if [[ ${v[0]} = BEAC ]];then
@@ -204,7 +205,7 @@ function brl {                                                                  
   [[ -f $p3 ]] || return;rm -f ${p3}r;bmi;local d=0000-00-00;local l=0;local n=0;local h=0;local g=0;while read -a o;do
     d=${o[3]};h=$g;g=$(grep -n "$d 23:58" ${p2}r|cut -d: -f1);[[ ${g:=$h} -le $h ]] && continue;dts $d\ ${o[4]};nn=${o[5]:4:2}                                # get next beacon log position
     nr=${o[6]};nm=${o[13]};nd=${o[14]};l2=$(brh $g|bfl 23:58);bo2 $d;((l+=b2));((n+=1));b3=$(nu5 $l/$n)                                                       # cur/avg homologous position
-    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${o[15]};b5=${o[12]};b7=${o[11]};bms;echo "$m" >> ${p3}r                                         # sum err arrays & new bmedias output
+    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${o[15]};b5=${o[12]};b7=${o[11]};bms;echo "$m" >> ${p3}r                                         # sum err arrays & new medias output
   done <<< $(cat $p3)
 }
 function bsl {                                                                                                                                                # shrink beacon log using barqivo
@@ -219,8 +220,8 @@ function bbt { [[ $(grep $d0 ${p2} 2>$s3|wc -l) -gt 0 ]]; }                     
 function bct { local n=$((nn-5));[[ $nm -ge $n && $(bl6 $hors) -eq 1 ]] && ( btt || sot ); }                                                                  # change configured peers test
 function bdl { local d=$(pt0 $1 sai);[[ -f $p2 && $d != sai ]] || return;cp $p2 ${p2}o;grep -v $d ${p2}o > $p2;grep $d ${p2}o > ${p2}d; }                     # delete beacon log day
 function nsh {
-  echo -e "ROUTES\t\t$(ip route show|grep 'default via'|grep -v linkdown|cut -d' ' -f3)\nDNS\t\t$(resolvectl|grep 'Current DNS'|cut -d' ' -f6)"               # routes
-  local v=0;for v in $(ip a|grep 'state UP'|cut -d: -f2);do echo -e "$v\t\t$(resolvectl dns|grep $v|cut -d' ' -f4-6)";done                                    # dns info
+  nex "ROUTES\t\t$(ip route show|grep 'default via'|grep -v linkdown|cut -d' ' -f3)\nDNS\t\t$(resolvectl|grep 'Current DNS'|cut -d' ' -f6)"               # routes
+  local v=0;for v in $(ip a|grep 'state UP'|cut -d: -f2);do nex "$v\t\t$(resolvectl dns|grep $v|cut -d' ' -f4-6)";done                                    # dns info
 }
 function cpe {                                                                                                                                                # system status
   local e='NO';[[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK';dts
@@ -237,14 +238,9 @@ function cpe {                                                                  
   local l=$(fs3|grep -i 'error' |wc -l);local n=$(fs2|grep -v ' INFO '|wc -l)
   local e=$(fs3|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'                                |cut -c1-53)
   local d=$(fs2|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
-  m="ERRO$(printf '%3i' $l) $(printf '%3i' $n) $dt";[[ $l -gt 0 ]] && m="$m system: $e";[[ $n -gt 0 ]] && m="$m ethrum: $d";(( l+n )) && echo -e "$m"         # sys/eth errors info
+  m="ERRO$(printf '%3i' $l) $(printf '%3i' $n) $dt";[[ $l -gt 0 ]] && m="$m system: $e";[[ $n -gt 0 ]] && m="$m ethrum: $d";(( l+n )) && echo "$m"         # sys/eth errors info
   m='';srt && m="$m, reboot $(($(sra)/60/60)) hours ago";[[ $(bsc) -gt 0 ]] && m="$m, committee on";[[ $m ]] && echo "INFO        $dt${m#*,}"                 # reboot/committee info
 }
-function uf1 { cex "ufw allow from $2 to any port $1 comment $3"; }
-function uf2 { cex "ufw allow $1 comment $2"; }
-function uf3 { cex "ufw deny  $1 comment $2"; }
-function uf4 { cex "ufw delete allow from $2 to any port $1"; }
-function uf5 { cex "ufw delete deny $1"; }
 # Plex Media Server
 function xop { uf5 32400     ;uf1 32400 192.168.8.0/24 plex; }
 function xcl { uf3 32400 plex;uf4 32400 192.168.8.0/24; }
@@ -292,7 +288,7 @@ function va  {
   [[ $(sst $n3) ]] || return                                                                                                                                  # continue if inactive\|failed
   if [[ -f $p1/vc_lock ]];then
     if [[ -f $p0/slashing_protection.sqlite ]];then                                                                                                           # slashing_protection
-      echo $H|sudo -S cp $p0/slashing_protection.sqlite $p8 2>$s3
+      cex "cp $p0/slashing_protection.sqlite $p8"
       sudo chown eth3:eth3 $p8/slashing_protection.sqlite
       sudo chmod 600 $p8/slashing_protection.sqlite
     fi
@@ -305,10 +301,10 @@ function pa  { [[ $(sst $n4) ]] && { cex "$w3 $n4"; } }
 function na  { [[ $(sst $n5) ]] && { cex "$w3 $n5"; } }
 function fa  { [[ $(sst $n6) ]] && { cex "$w3 $n6"; } }
 function wa  {
-  if [[ $(echo $H|sudo -S ufw status 2>$s3|grep -i inactive) ]];then
-    echo -e "${i}UFW ENABLE${f}";sudo ufw enable <<< y                                                                                                        # enable asks: Proceed with operation (y|n)?
+  if [[ $(pex 'ufw status'|grep -i inactive) ]];then
+    tex "UFW ENABLE";sudo ufw enable <<< y                                                                                                        # enable asks: Proceed with operation (y|n)?
   else
-    echo -e "${i}FIREWALL ALREADY ACTIVE${f}"
+    tex "FIREWALL ALREADY ACTIVE"
   fi
 }
 # para/disable goethereum/beacon/validator/prometheus/grafana
@@ -326,15 +322,15 @@ function nd  { [[ $(sst $n5 loaded) ]] && { cex "$w5 $n5"; } }
 function fd  { [[ $(sst $n6 loaded) ]] && { cex "$w5 $n6";uf3 3000/tcp;sex 'ufw reload'; } }
 function dpa { cex "$w2 $o2";sex "$w2 systemd-resolved";cex "$w3 $o2";sex "$w3 systemd-resolved"; }                                                           # DNS stop/start
 function ssp {
-  echo -e "${i}QUER MESMO TRANSFERIR VALIDATORS?${f}";read rsp
+  tex "QUER MESMO TRANSFERIR VALIDATORS?";read rsp
   if [[ $rsp = sim && ! -f $p1/vc_slash && ! -f $p1/vc_lock && -f $p1/vc_keys ]];then
     vp;vd
-    echo -e "${i}SAVE SLASHING PROTECTION DB${f}"
-    echo $H|sudo -S cp $p8/slashing_protection.sqlite $p0 2>$s3;sudo chown eth:eth $p0/slashing_protection.sqlite
+    tex "SAVE SLASHING PROTECTION DB"
+    cex "cp $p8/slashing_protection.sqlite $p0";sudo chown eth:eth $p0/slashing_protection.sqlite
     if [[ $cunm = $znm3 ]];then
-      scp $p0/slashing_protection.sqlite vpss:~         ;echo -e "${i}SAVED SLASHING PROTECTION DB IN vpss${f}"
+      scp $p0/slashing_protection.sqlite vpss:~         ;tex "SAVED SLASHING PROTECTION DB IN vpss"
     else
-      scp $p0/slashing_protection.sqlite ztc3.fruga.pt:~;echo -e "${i}SAVED SLASHING PROTECTION DB IN ztc3${f}"
+      scp $p0/slashing_protection.sqlite ztc3.fruga.pt:~;tex "SAVED SLASHING PROTECTION DB IN ztc3"
     fi
   fi
 }
@@ -347,7 +343,7 @@ function paf { t2t && sex "$p0/eth2/t5 cputurbo"; }                             
 function jw0 { openssl rand -hex 32|tr -d '\n'|tee jwt 1>$s3;[[ -f jwt ]] && jw4; }
 function jw1 { sex "cp jwt $2";sex "chown $1:$1 $2/jwt"; }
 function jw3 { scp jwt $1:~;ssh $1 "export H=$H;eth2/t6 jwt"; }
-function jw4 { chmod 644 jwt;jw3 ztc2;jw3 ztc3;jw1 eth1 $p9/geth; }
+function jw4 { chmod 600 jwt;jw3 ztc2;jw3 ztc3;jw1 eth1 $p9/geth; }
 function sr0 { cp $s4/$n0.service $n0.sav;sed "s%peers *\([0-9]*\)%peers \1 --authrpc.addr $zip1 --authrpc.jwtsecret $p9/geth/jwt%" $n0.sav > $n0.jwt;sr9 $n0; }
 function sr1 { cp $s4/$n1.service $n1.sav;sed "s%--eth1-endpoints *\([^,]*:8545\)[^ ]*%--execution-endpoint http://$zip1:8551 --execution-jwt $p7/jwt --suggested-fee-recipient $a0%" $n1.sav > $n1.jwt;sr9 $n1; }
 function sr3 { cp $s4/$n3.service $n3.sav;sed "s%beacon-nodes *\([^,]*:5052\)[^ ]*%beacon-nodes \1,http://$zip2:5052 --suggested-fee-recipient $a0%" $n3.sav > $n3.jwt;sr9 $n3; }
@@ -369,7 +365,7 @@ function sr9 { chmod 644 $1.jwt;sex "mv $1.jwt $s4/$1.jwt"; }
 [[ $1 = bn  ]] && { bm0;bno;echo "$m"; }
 [[ $1 = blf ]] && { bl0;echo "$m" >> $p2;stt && bo5 && bht && bst && bdl $d0;[[ $ok != OK ]] && b1r 0;pas; }                                                  # beacon log/delete day/restart & parameter set
 [[ $1 = bmf ]] && { bm0;bms;bbt && echo "$m" >> $p3;bct && b1r $b4 $(brb PE) 120; }
-[[ $1 = bnf ]] && { bm0;bno;echo -e "$m" >> $p6; }
+[[ $1 = bnf ]] && { bm0;bno;echo "$m" >> $p6; }
 [[ $1 = gh  ]] && { gh0 $2; }
 [[ $1 = bh  ]] && { bh0 $2; }
 [[ $1 = bhs ]] && { bm0;bms;[[ -f $p2 ]] && echo "$m";sso BEAC $n1;[[ $(sst $n3 loaded) ]] && sso VALI $n3;cpe; }                                             # lighthouse services & system report
@@ -509,7 +505,7 @@ if [[ ! $1 ]];then
   m="$m\nel [hh:mm]\tgeth/lighthouse log lines"
   m="$m\nll [hh:mm]\tgeth/lighthouse all log lines"
   m="$m\nnl [hh:mm]\tbeacon node     log lines"
-  m="$m\nbrl\t\trecalculate beacon/bmedias logs"
+  m="$m\nbrl\t\trecalculate beacon/medias logs"
   m="$m\nbsl\t\tshrink beacon log using barqivo"
   m="$m\nbdl yyyy-mm-dd\tdelete beacon log day"
   m="$m\nbo  [lines]\thomologous report [with max lines]"
@@ -530,5 +526,5 @@ if [[ ! $1 ]];then
   m="$m\nnrs\t\tdns/netplan reset"
   m="$m\ndrs\t\tdns reset"
   m="$m\ntrs\t\ttime sync restart"
-  echo -e "\n$m\n"
+  nex "\n$m\n"
 fi
