cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -49,6 +49,7 @@ function gl  {                                                                  
     m=" NOT RUNNING $(dts)"
   fi
 }
+function gh  { [[ ! -f $p5 ]] && return;tail -n${1:-$hors} $p5;[[ $1 ]] && return;gl;echo -e "GETH$m\n";sst GETH $ethg;cpe; }                     # geth historic report
 function grs { rd4 $ethg $1 $(gv) 10 15;sex "systemctl start $ethg";sleep 20s;echo "GETH RESTAR $(dnn $(dts) $(gv) $(gq))" >> $p5; }              # change/stop/load/start/log geth restart
 # beacon control commands
 function bv  { nu0 $(fs1 $ethb target-peers [0-9])                   ; }                                                                          # get configured peers
@@ -77,16 +78,30 @@ function bl  {                                                                  
     m=" NOT RUNNING $(dts)"
   fi
 }
-function bm  {
+function bm  {                                                                                                                                    # bmedias report
   bm0;b4=0;b8=$(fs4 'reduce peer'|wc -l);dt=$(dts);nn=$(bv);nr=$(bq)                                                                              # ini arrays/vars
   [[ -f $p7         ]] && bm3;b6=$(tail -n$(($(bk)-o[1])) $p2 2>/dev/null|grep BEAC);[[ $b6 ]] && bm1 20;bm2                                      # set arrays from barqivo log & remaining beacon log
   [[ ${b2:-0} -eq 0 ]] && bo1;b3=$(nu6 $(sed -Ee 's%BEAC +[0-9]+ +([0-9]+).+%\1%' $p3 2>/dev/null))                                               # cur/avg homologous position
   bm5 ${a[$nn]} 20;[[ $(nu3 ${a[$nn]}) -le $(nu3 ${a[0]}) || $(bs $hors) -gt 1 ]] && b4=0;bmo;bno                                                 # change configured peers & outputs
 }
-function bh  {
+function bh  {                                                                                                                                    # beacon historic report
+  [[ ! -f $p2 ]] && return                                                                                                                        # beacon log must exist
   tail -n${1:-$hors} $p2;[[ $1 ]] && return;bo1;echo -e "BO$(printf '%5i' $(echo "$b1"|wc -l)) $(printf '%3i' $b2)";bo2                           # beacon log/homologous report
   bl;echo -e "BL$(printf '%9i' $(cat $p2 2>/dev/null|wc -l))\nBEAC$m";bm;echo -e "BM$(printf '%5i' $(cat $p3 2>/dev/null|wc -l))\nBEAC$m"         # beacon/medias report
-  sst BEAC $ethb;sst VALI $ethv;csh;psh;esh                                                                                                       # beacon/validator status & clock/cpu/system/eth info
+  sst BEAC $ethb;sst VALI $ethv;cpe                                                                                                               # beacon/validator status & clock/cpu/system/eth info
+}
+function bo1 {                                                                                                                                    # homologous lines/position
+  b2=0;[[ ! -f $p2 ]] && return                                                                                                                   # beacon log must exist
+  local t=00:00;[[ $(fs2 $1) ]] && b2=$1;[[ $(fs2 $2) ]] && b2=$2;[[ $(fs3 $1) ]] && t=$1;[[ $(fs3 $2) ]] && t=$2                                 # homologous position/time forced
+  local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\).*%\1\t\2%')                                               # last yyyy-mm-dd hh:mm beacon log
+  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2);b1=$(grep "BEAC.*$t" $p2);[[ $b2 -eq 0 ]] && b2=$(echo "$b1"|bt $d)     # set homologous lines/position
+  local n=0;while [[ ${b2:-0} -eq 0 && $n -lt 50 ]];do ((n+=1));d=$(date -d "$n days ago $t" '+%Y-%m-%d');b2=$(echo "$b1"|bt $d);done             # search past homologous info (max 50 days)
+}
+function bo2 {                                                                                                                                    # homologous report
+  [[ ! -f $p2 ]] && return;local g=${b2:-0};local d=${b2:-0}                                                                                      # init head/tail lines
+  if [[ $(fs2 $1) ]];then g=$1;else if [[ $g -lt $l2rs && $(echo "$b1"|wc -l) -ge $l2rs ]];then d=$l2rs;g=$l2rs;fi;fi                             # ajust head lines
+  if [[ $(fs2 $1) ]];then d=$1;else if [[ $d -gt $hors                                  ]];then d=$hors        ;fi;fi                             # ajust tail lines
+  echo "$b1"|bf|head -n$g|tail -n$d                                                                                                               # order/filter homologous report
 }
 function blo {
   #    0  1   2          3     4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18     19  20  21   22   23   24         25   26
@@ -120,31 +135,16 @@ function bm2 {
 function bm3 { read -a o <<< $(tail -n1 $p7);bmk 20;bmz 20;bmx 20;bmw 20;bmc 20; }                                                                # set penalty arrays from barqivo log
 function bm4 { k[$1]=0;z[$1]=0;x[$1]=0;w[$1]=0;c[$1]=0;a[$1]=0;[[ $1 -lt 50 ]] && bm4 $(($1+5)); }                                                # recursively ini penalty arrays
 function bm5 { local g=$1;if [[ $(nu3 ${a[$2]}) -lt $(nu3 $g) ]];then b4=$(($2-nn));g=${a[$2]};fi;[[ $2 -lt 50 ]] && bm5 $g $(($2+5)); }          # recursively compare avg/cur penalties & get min
-function bmk { local g=${2:-19};k[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmk $(($1+5)) $((g-1)); }                                                       # recursively set missing           err array
-function bmz { local g=${2:-27};z[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmz $(($1+5)) $((g-1)); }                                                       # recursively set failed target     err array
-function bmx { local g=${2:-35};x[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmx $(($1+5)) $((g-1)); }                                                       # recursively set failed head       err array
-function bmw { local g=${2:-43};w[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmw $(($1+5)) $((g-1)); }                                                       # recursively set sub-optimal delay err array
-function bmc { local g=${2:-11};c[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmc $(($1+5)) $((g-1)); }                                                       # recursively set                   cnt array
+function bmk { local g=${2:-19};k[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmk $(($1+5)) $((g-1))  ; }                                                     # recursively set missing           err array
+function bmz { local g=${2:-27};z[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmz $(($1+5)) $((g-1))  ; }                                                     # recursively set failed target     err array
+function bmx { local g=${2:-35};x[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmx $(($1+5)) $((g-1))  ; }                                                     # recursively set failed head       err array
+function bmw { local g=${2:-43};w[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmw $(($1+5)) $((g-1))  ; }                                                     # recursively set sub-optimal delay err array
+function bmc { local g=${2:-11};c[$1]=${o[$g]};[[ $1 -lt 50 ]] && bmc $(($1+5)) $((g-1))  ; }                                                     # recursively set                   cnt array
 function bnk { if [[ $1 -ge 20 ]];then bnk $(($1-5)) "$2$3${k[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum missing           err array
 function bnz { if [[ $1 -ge 20 ]];then bnz $(($1-5)) "$2$3${z[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum failed target     err array
 function bnx { if [[ $1 -ge 20 ]];then bnx $(($1-5)) "$2$3${x[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum failed head       err array
 function bnw { if [[ $1 -ge 20 ]];then bnw $(($1-5)) "$2$3${w[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum sub-optimal delay err array
 function bnc { if [[ $1 -ge 20 ]];then bnc $(($1-5)) "$2$3${c[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum                   cnt array
-function bo1 {                                                                                                                                    # homologous lines/position
-  b2=0;[[ ! -f $p2 ]] && return                                                                                                                   # beacon log must exist
-  local t=00:00;[[ $(fs2 $1) ]] && b2=$1;[[ $(fs2 $2) ]] && b2=$2;[[ $(fs3 $1) ]] && t=$1;[[ $(fs3 $2) ]] && t=$2                                 # homologous position/time forced
-  local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\).*%\1\t\2%')                                               # last yyyy-mm-dd hh:mm beacon log
-  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2)
-  b1=$(grep "BEAC.*$t" $p2);[[ $b2 -eq 0 ]] && b2=$(echo "$b1"|bt $d)                                                                             # homologous lines/position
-  local n=0;while [[ ${b2:-0} -eq 0 && $n -lt 50 ]];do ((n+=1));d=$(date -d "$n days ago $t" '+%Y-%m-%d');b2=$(echo "$b1"|bt $d);done             # search past homologous info (max 50 days)
-}
-function bo2 {                                                                                                                                    # homologous report
-  [[ ! -f $p2 ]] && return                                                                                                                        # beacon log must exist
-  local g=${b2:-0};local d=${b2:-0}                                                                                                               # init head/tail lines
-  if [[ $(fs2 $1) ]];then g=$1;else if [[ $g -lt $l2rs && $(echo "$b1"|wc -l) -ge $l2rs ]];then d=$l2rs;g=$l2rs;fi;fi                             # ajust head lines
-  if [[ $(fs2 $1) ]];then d=$1;else if [[ $d -gt $hors                                  ]];then d=$hors        ;fi;fi                             # ajust tail lines
-  echo "$b1"|bf|head -n$g|tail -n$d                                                                                                               # filter homologous report
-}
 function brs {                                                                                                                                    # beacon/validator restart
   [[ -f $p0/beacon.restart.inicio ]] && return;touch $p0/beacon.restart.inicio;local n=0                                                          # se restart flag existe exit
   while [[ -f $p0/beacon.restart.inicio && $n -lt 300 ]]; do                                                                                      # procura posicao ideal restart
@@ -167,18 +167,16 @@ function brl {                                                                  
   [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p3}new ]] && rm ${p3}new
   unset v;while read -a v;do ok=${v[1]};dt=${v[3]}\ ${v[4]};nn=$(bx ${v[5]});nr=${v[6]}                                                           # uncalculated vars
     if [[ ${v[0]} = BEAC ]];then
-      b5=${v[26]};b0=${v[13]};z1=${v[19]};z2=${v[20]};z3=${v[22]};z4=${v[23]};bn ${v[11]} ${v[15]} ${v[16]} ${v[17]} ${v[18]};blo                 # calculated output
+      b5=${v[26]};b0=${v[13]};z1=${v[19]};z2=${v[20]};z3=${v[22]};z4=${v[23]};bn ${v[11]} ${v[15]} ${v[16]} ${v[17]} ${v[18]};blo                 #  BEAC lines calculated output
     else
-      m=" $ok $(printf '%3i' ${v[2]}) $(dnn $dt $nn $nr)"                                                                                         # other lines
-    fi;echo "${v[0]}$m" >> ${p2}new                                                                                                               # new beacon log output
+      m=" $ok $(printf '%3i' ${v[2]}) $(dnn $dt $nn $nr)"                                                                                         # !BEAC lines
+      fi                       ;echo "${v[0]}$m" >> ${p2}new                                                                                      # new beacon log output
   done <<< $(cat $p2)
-  [[ ! -f $p3 ]] && return
-  bm0;local d='0000-00-00';local e='23:58';local l=0;local n=0;local h=0;local g=0
-  while read -a o;do
-    d=${o[3]};h=$g;g=$(grep -n "$d $e" ${p2}new|cut -d: -f1);dt=${o[3]}\ ${o[4]};nn=$(bx ${o[5]});nr=${o[6]}                                    # beacon log position & uncalculated vars
-    b2=$(head -n$g ${p2}new|grep "BEAC.*$e"|bt $d);((l+=b2));((n+=1));b3=$(nu3 $l/$n 5 1)                                                       # cur/avg homologous position
-    b6=$(head -n$g ${p2}new|tail -n$((g-h))|grep BEAC);[[ $b6 ]] && bm1 20;bm2                                                                  # sum paid err arrays from interim beacon log
-    b4=${o[18]};b8=${o[19]};bmo;echo "${o[0]}$m" >> ${p3}new                                                                                    # new bmedias log output
+  [[ ! -f $p3 ]] && return;bm0;local d='0000-00-00';local e='23:58';local l=0;local n=0;local h=0;local g=0;while read -a o;do
+    d=${o[3]};h=$g;g=$(grep -n "$d $e" ${p2}new|cut -d: -f1);dt=${o[3]}\ ${o[4]};nn=$(bx ${o[5]});nr=${o[6]}                                      # beacon log position & uncalculated vars
+    b2=$(head -n$g ${p2}new|grep "BEAC.*$e"|bt $d);((l+=b2));((n+=1));b3=$(nu3 $l/$n 5 1)                                                         # cur/avg homologous position
+    b6=$(head -n$g ${p2}new|tail -n$((g-h))|grep BEAC);[[ $b6 ]] && bm1 20;bm2                                                                    # sum paid err arrays from interim beacon log
+    b4=${o[18]};b8=${o[19]};bmo;echo "${o[0]}$m" >> ${p3}new                                                                                      # new bmedias log output
   done <<< $(cat $p3)
 }
 function bsl {                                                                                                                                    # shrink beacon log using barqivo
@@ -195,19 +193,15 @@ function nsh {                                                                  
   echo -e "ROUTES\t\t$(ip route show|grep 'default via'|grep -v linkdown|cut -d' ' -f3)\nDNS\t\t$(resolvectl|grep 'Current DNS'|cut -d' ' -f6)"
   local v=0;for v in $(ip a|grep 'state UP'|cut -d: -f2);do echo -e "$v\t\t$(resolvectl dns|grep $v|cut -d' ' -f4-6)";done
 }
-function csh {                                                                                                                                    # system clock info
-  local e='NO';[[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK'
+function cpe {                                                                                                 
+  local e='NO';[[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK'                                   # system clock info
   echo "CLCK $e $(printf '%3i' $(fs7 'check system clock'|wc -l)) $(dts) status: $(fs1 systemd-timesyncd)"
-}
-function psh {                                                                                                                                    # cpu info
-  local l=0;local n=0;local v=0
+  [[ $1 = c ]] && return;local l=0;local n=0;local v=0                                                                                            # cpu info
   local e=$(fs7 'ture/speed normal'|tail -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
   local d=$(fs7 'e above threshold'|head -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
   for v in $(sensors 2>/dev/null|grep 'Package\|Core'|sed 's%.*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\1%');do n=$((n+1));l=$(nu1 $l$v 1);done
   [[ $e ]] && e="normal: $e";[[ $d ]] && d="throttled: $d";echo "TEMP $(nu3 $l/$(nu7 $n) 1 1 %5.1fC) $(dts) $d $e"
-}
-function esh {                                                                                                                                    # system/eth status info
-  local l=$(fs5|grep -i 'error' |wc -l);local n=$(fs6|grep -v ' INFO '|wc -l)
+  [[ $1 = p ]] && return;local l=$(fs5|grep -i 'error' |wc -l);local n=$(fs6|grep -v ' INFO '|wc -l)                                              # system/eth status info
   local e=$(fs5|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'|cut -c1-53)
   local d=$(fs6|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
   m="ERRO $(printf '%2i' $l) $(printf '%3i' $n) $(dts)";[[ $l -gt 0 ]] && m="$m sys: $e";[[ $n -gt 0 ]] && m="$m eth2: $d";echo "$m"
@@ -313,7 +307,7 @@ function ssp {
 [[ $1 = drs ]] && { echo RESET DNS;rd0;rd1; }
 [[ $1 = nrs ]] && { echo RESET DNS \& NETPLAN;cex 'netplan apply';rd0;rd1; }
 [[ $1 = nsh ]] && { nsh; }
-[[ $1 = trs ]] && { [[ $(fs0 systemd-timesyncd masked) ]] || { cex 'systemctl restart systemd-timesyncd'; };csh; }
+[[ $1 = trs ]] && { [[ $(fs0 systemd-timesyncd masked) ]] || { cex 'systemctl restart systemd-timesyncd'; };cpe c; }
 [[ $1 = vcp ]] && { ssp; }
 [[ $1 = gl  ]] && { gl;echo -e "GETH$m"; }
 [[ $1 = glf ]] && { gl;echo -e "GETH$m" >> $p5; }
@@ -323,13 +317,13 @@ function ssp {
 [[ $1 = blf ]] && { bl;echo -e "BEAC$m" >> $p2; }
 [[ $1 = bmf ]] && { bm;echo -e "BEAC$m" >> $p3; }
 [[ $1 = bnf ]] && { bm;echo -e "BEAC$s" >> $p7; }
-[[ $1 = gh  ]] && { [[ -f $p5           ]] && { tail -n${2:-$hors} $p5;[[ $2 ]] || { gl;echo -e "GETH$m\n";sst GETH $ethg;csh;psh;esh; } } }
-[[ $1 = bh  ]] && { [[ -f $p2           ]] && bh $2; }
+[[ $1 = gh  ]] && { gh $2; }
+[[ $1 = bh  ]] && { bh $2; }
+[[ $1 = bo  ]] && { bo1 $2 $3;bo2 $2; }
 [[ $1 = brl ]] && { [[ -f $p2           ]] && brl; }
 [[ $1 = bsl ]] && { [[ -f $p2 && -f $p7 ]] && bsl; }
 [[ $1 = bnl ]] && { bnl; }
-[[ $1 = bo  ]] && { bo1 $2 $3;bo2 $2; }
-[[ $1 = cpe ]] && { csh;psh;esh; }
+[[ $1 = cpe ]] && { cpe; }
 [[ $1 = glr ]] && { gb;[[ $ok != OK ]] && grs 0; }
 [[ $1 = blr ]] && { bb;[[ $ok != OK ]] && brs 0; }
 [[ $1 = bmc ]] && { bm;[[ $b4 -ne 0 ]] && brs $b4 PE; }
