cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -29,8 +29,8 @@ function gv { nu0 $(fs1 $ethg maxpeers [0-9])                                   
 function gq { nu0 $(geth attach "http://$cgth:8545" --exec net.peerCount 2>/dev/null); }                                      # current peers
 function gy { geth attach "http://$cgth:8545" --exec eth.syncing         2>/dev/null ; }                                      # current syncing status
 function gb {
-  g0=$(echo $H|sudo -S grep 'mported new' $p4 2>/dev/null|wc -l);ok='OK'                                                      # g0 numero de new imported chain segments
-  [[ $g0 -eq $(grep sgs: $p5 2>/dev/null|tail -n1|sed 's%.*sgs: *\([0-9]*\).*%\1%') ]] && ok='BK'                             # ok OK/BK blocked
+  g0=$(echo $H|sudo -S grep 'mported new' $p4 2>/dev/null|wc -l)                                                              # numero de new imported chain segments
+  ok=OK;[[ $g0 -eq $(grep sgs: $p5 2>/dev/null|tail -n1|sed 's%.*sgs: *\([0-9]*\).*%\1%') ]] && ok=BK                         # OK/BK
 }
 function gl {
   if [[ $(fs0 $ethg running) ]];then
@@ -60,44 +60,48 @@ function bw { echo $((10*z1)); }                                                
 function br { echo $((90*z3)); }                                                                                              # numerator general errors restart index
 function bu { echo $(($(nu3 200 $(bz) $z5)+$(nu3 100 $(bw) $z2)+$(nu3 100 $(br) $z4))); }                                     # restart index
 function bs { tail -n$1 $p2 2>/dev/null|cut -d' ' -f1|sort -u|wc -l; }                                                        # log restart activity test
-function bk { cat       $p2 2>/dev/null|                      wc -l; }                                                        # log line count
+function bk { cat       $p2 2>/dev/null                      |wc -l; }                                                        # log line count
 function bb {
-  local e=$(echo $H|sudo -S grep "lighthouse.$bpid" $p4 2>/dev/null|tail -n3600)
-  z1=$(echo "$e"|grep 'rocessed block'|wc -l);z2=$(echo "$e"|grep 'block received'|wc -l);z3=$(echo "$e"|grep -v ' INFO '|wc -l);z4=$(echo "$e"|grep ' INFO '|wc -l)
-  z5=$(echo $(echo $H|sudo -S grep 'attestation(s) success' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  z6=$(echo $(echo $H|sudo -S grep 'attestation(s) missing' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  z7=$(echo $(echo $H|sudo -S grep 'attestation(s).*target' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  z8=$(echo $(echo $H|sudo -S grep 'attestation(s).*head'   $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  z9=$(echo $(echo $H|sudo -S grep 'attestation(s) had'     $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  ok='OK';local g=$(bu);[[ $g -ge $l1rs ]] && if [[ $g -ge $l2rs ]];then [[ $(bs $l2rs) -eq 1 ]] && ok='BK';else [[ $(bs $hors) -eq 1 ]] && ok='BK';fi
+  local e=$(echo $H|sudo -S grep "lighthouse.$bpid" $p4 2>/dev/null|tail -n3600)                                              # last beacon log messages
+  z1=$(echo "$e"|grep 'rocessed block'|wc -l);z2=$(echo "$e"|grep 'block received'|wc -l)                                     # processed blocks restart index vars
+  z3=$(echo "$e"|grep -v ' INFO '     |wc -l);z4=$(echo "$e"|grep ' INFO '        |wc -l)                                     # general errors restart index vars
+  z5=$(echo $H|sudo -S grep 'attestation(s) success' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w)           # denominator paid errors restart index
+  z6=$(echo $H|sudo -S grep 'attestation(s) missing' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w)           # missing part for paid errors restart index
+  z7=$(echo $H|sudo -S grep 'attestation(s).*target' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w)           # failed to match target part for paid errors restart index
+  z8=$(echo $H|sudo -S grep 'attestation(s).*head'   $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w)           # failed to match head part for paid errors restart index
+  z9=$(echo $H|sudo -S grep 'attestation(s) had'     $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w)           # had sub-optimal inclusion delay part for paid errors restart index
+  ok=OK;local g=$(bu);[[ ($g -ge $l1rs && $(bs $hors) -eq 1) || ($g -ge $l2rs && $(bs $l2rs) -eq 1) ]] && ok=BK               # OK/BK
 }
 function bl {
-  local l=0;local n=0;local v=0;for v in $(echo $H|sudo -S grep 'delay_ms: [0-9]' $p4 2>/dev/null|sed 's%.*delay_ms: *\([0-9]*\).*%\1%');do n=$((n+1));l=$((l+v));done
-  if [[ $n -gt 0  ]];then b5=$((l/n));b6=$(echo $H|sudo -S grep 'published block' $p4 2>/dev/null|wc -l);dt=$(dts);nn=$(bv);nr=$(bq);bb;blo;else m=" NOT HERE $(dts)";fi
+  local l=0;local n=0;local v=0;for v in $(echo $H|sudo -S grep 'delay_ms: [0-9]' $p4 2>/dev/null|sed 's%.*delay_ms: *\([0-9]*\).*%\1%');do n=$((n+1));l=$((l+v));done   # delays in service logs
+  if [[ $n -gt 0  ]];then b5=$((l/n));b6=$(echo $H|sudo -S grep 'published block' $p4 2>/dev/null|wc -l);dt=$(dts);nn=$(bv);nr=$(bq);bb;blo;else m=" NOT HERE $(dts)";fi # obtaim log output
 }
 function bm {
   bm0;dt=$(dts);nn=$(bv);nr=$(bq);local g=0
   if [[ -f $p7 ]];then
-    unset o;read -a o <<< $(tail -n1 $p7);g=${o[1]}
+    unset o;read -a o <<< $(tail -n1 $p7);g=${o[1]}                                                                           # init vars from last line of barqivo log
     k[50]=${o[13]};k[45]=${o[14]};k[40]=${o[15]};k[35]=${o[16]};k[30]=${o[17]};k[25]=${o[18]};k[20]=${o[19]}
     z[50]=${o[21]};z[45]=${o[22]};z[40]=${o[23]};z[35]=${o[24]};z[30]=${o[25]};z[25]=${o[26]};z[20]=${o[27]}
     x[50]=${o[29]};x[45]=${o[30]};x[40]=${o[31]};x[35]=${o[32]};x[30]=${o[33]};x[25]=${o[34]};x[20]=${o[35]}
     w[50]=${o[37]};w[45]=${o[38]};w[40]=${o[39]};w[35]=${o[40]};w[30]=${o[41]};w[25]=${o[42]};w[20]=${o[43]}
     c[50]=${o[ 5]};c[45]=${o[ 6]};c[40]=${o[ 7]};c[35]=${o[ 8]};c[30]=${o[ 9]};c[25]=${o[10]};c[20]=${o[11]}
   fi
-  [[ -f $p2 ]] && { unset v;while read -a v;do bm1;done <<< $(tail -n$(($(bk)-g)) $p2|grep BEAC); };bm2;[[ ${b2:-0} -eq 0 ]] && bo1
-  local l=0;local n=0;[[ -f $p3 ]] && { unset v;while read -a v;do l=$((${v[2]}+l));n=$((1+n));done <<< $(cat $p3); };b3=$(nu2 "($l+$b2)/(1+$n)" 5)
-  b4=0;bmn ${a[$nn]};[[ $b2 -le $b3 || $(bs $hors) -gt 1 ]] && b4=0;bmo;bno
+  [[ -f $p2 ]] && { unset v;while read -a v;do bm1;done <<< $(tail -n$(($(bk)-g)) $p2|grep BEAC); }                           # add data from additional beacon lines log
+  [[ ${b2:-0} -eq 0 ]] && bo1;bm2;local l=0;local n=0                                                                         # cur homologous position & totalized data
+  [[ -f $p3 ]] && { unset v;while read -a v;do l=$((${v[2]}+l));n=$((1+n));done <<< $(cat $p3)  ; }                           # avg homologous position
+  b3=$(nu2 "($l+$b2)/(1+$n)" 5);b4=0;bmn ${a[$nn]};[[ $b2 -le $b3 || $(bs $hors) -gt 1 ]] && b4=0;bmo;bno                     # arithmetic change configured peers & obtaim medias/arquivo outputs
 }
 function bh {
-  tail -n${1:-$hors} $p2
-  [[ $1 ]] || { bo1;echo -e "BO$(printf '%5i' $(echo "$b1"|wc -l)) $(printf '%3i' $b2)";bo2; }
-  [[ $1 ]] || { bl ;echo -e "BL$(printf '%9i' $(cat $p2 2>/dev/null|wc -l))\nBEAC$m"; }
-  [[ $1 ]] || { bm ;echo -e "BM$(printf '%5i' $(cat $p3 2>/dev/null|wc -l))\nBEAC$m"; }
-  [[ $1 ]] || { sst BEAC $ethb;sst VALI $ethv; }
+  tail -n${1:-$hors} $p2                                                                                                      # beacon log last lines
+  [[ $1 ]] || { bo1;echo -e "BO$(printf '%5i' $(echo "$b1"|wc -l)) $(printf '%3i' $b2)";bo2; }                                # homologous report
+  [[ $1 ]] || { bl ;echo -e "BL$(printf '%9i' $(cat $p2 2>/dev/null|wc -l))\nBEAC$m"; }                                       # cur log report
+  [[ $1 ]] || { bm ;echo -e "BM$(printf '%5i' $(cat $p3 2>/dev/null|wc -l))\nBEAC$m"; }                                       # medias report
+  [[ $1 ]] || { sst BEAC $ethb;sst VALI $ethv; }                                                                              # beacon/validator services status
 }
-# recursively compare avg penalty array with current penalty
-function bmn { local g=$1;local n=${2:-20};if [[ $(nu2 ${a[$n]}*100) -lt $(nu2 $g*100) ]];then b4=$((n-nn));g=${a[$n]};fi;[[ $n -lt 50 ]] && bmn $g $((n+5)); }
+function bmn {
+  local g=$1;local n=${2:-20}
+  if [[ $(nu2 ${a[$n]}*100) -lt $(nu2 $g*100) ]];then b4=$((n-nn));g=${a[$n]};fi;[[ $n -lt 50 ]] && bmn $g $((n+5))           # recursively compare avg with cur penalties
+}
 function blo {
   #    0  1   2          3              4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18     19  20  21   22   23   24         25   26
   # BEAC OK   0 2021-11-22 17:15:58+00:00 node00: 32 reward_penalty: 224 3.54 attestation_block: 2950 2280 0 erros: 2 14 131 29      0 537   0   14 3586 1260     delay: 1000
@@ -127,10 +131,11 @@ function bm1 { local n=$(bx ${v[5]});k[$n]=$((k[n]+v[15]));z[$n]=$((z[n]+v[16]))
 function bm2 {
   k[00]=$((k[20]+k[25]+k[30]+k[35]+k[40]+k[45]+k[50]));z[00]=$((z[20]+z[25]+z[30]+z[35]+z[40]+z[45]+z[50]))
   x[00]=$((x[20]+x[25]+x[30]+x[35]+x[40]+x[45]+x[50]));w[00]=$((w[20]+w[25]+w[30]+w[35]+w[40]+w[45]+w[50]))
-  c[00]=$((c[20]+c[25]+c[30]+c[35]+c[40]+c[45]+c[50]));a[00]=$(bi 00);a[20]=$(bi 20);a[25]=$(bi 25);a[30]=$(bi 30);a[35]=$(bi 35);a[40]=$(bi 40);a[45]=$(bi 45);a[50]=$(bi 50)
+  c[00]=$((c[20]+c[25]+c[30]+c[35]+c[40]+c[45]+c[50]))
+  a[00]=$(bi 00);a[20]=$(bi 20);a[25]=$(bi 25);a[30]=$(bi 30);a[35]=$(bi 35);a[40]=$(bi 40);a[45]=$(bi 45);a[50]=$(bi 50)
 }
 function bo1 {
-  b2=0
+  b2=0                                                                                                                        # homologous position
   if [[ -f $p2 ]];then
     local e='00:00';local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\):.*%\1 \2%');local d=$(echo $l|cut -d' ' -f1);local n=0
     if [[ $(echo $1|egrep '^[0-9]+:[0-9]+$') ]];then e=$1 ;else if [[ $(echo $2|egrep '^[0-9]+:[0-9]+$') ]];then e=$2 ;else e=$(echo $l|cut -d' ' -f2);fi;fi;b1=$(grep "BEAC.*$e" $p2)
@@ -178,13 +183,13 @@ function brs {
     while [[ -f /home/eth/beacon.restart.inicio && $n -lt 200 ]]; do
       local l=$(echo $H|sudo -S grep "lighthouse.$bpid.* INFO " $p4 2>/dev/null|tail -n$pors|sed 's%.* INFO \([^ ]*\) .*%\1%'|sort -u)
       if [[ $(echo "$l"|wc -l) -eq 2 && $(echo "$l"|head -n1) = New && $(echo "$l"|tail -n1) = Synced ]];then
-        ok=${2:-$ok}
-        [[ $1 -ne 0 ]] && chp $ethb $1 $(bv) 20 50;epr $ethb;[[ $2 = VC ]] && sex "systemctl stop $ethv"                      # change config & stop service & daemon-reload
+        ok=${2:-$ok}                                                                                                          # ${PE|RB|BN|VC:-OK|BK}
+        [[ $1 -ne 0 ]] && chp $ethb $1 $(bv) 20 50;epr $ethb;[[ $2 = VC ]] && sex "systemctl stop $ethv"                      # change config & stop beacon & daemon-reload [& stop validator]
         if [[ $2 = RB ]];then
           echo "RSTI $ok $(printf '%3i' $n) $(dnn $(dts) $(bv) $(bq))" >> $p2
           rm -f /home/eth/beacon.restart.inicio;sex reboot
         else
-          sex "systemctl start $ethb";[[ $2 = VC ]] && sex "systemctl start $ethv"                                            # start service with new config
+          sex "systemctl start $ethb";[[ $2 = VC ]] && sex "systemctl start $ethv"                                            # start services with new config
           echo "RSTI $ok $(printf '%3i' $n) $(dnn $(dts) $(bv) $(bq))" >> $p2
         fi
         rm -f /home/eth/beacon.restart.inicio
