cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -43,7 +43,7 @@ function gy  {            geth attach --exec eth.syncing   "http://$cgth:8545" 2
 function gi  { echo $@|sed 's%.*highestBlock: *\([0-9]*\).*%\1%'; }                                                                                           # get highest geth block
 function gc  { echo $@|sed 's%.*currentBlock: *\([0-9]*\).*%\1%'; }                                                                                           # get current geth block
 function gb  { g0=$(fs0 Imported 0 geth|wc -l);ok=OK;[[ $g0 -eq $(lg0 .*sgs:) ]] && ok=BK; }                                                                  # imported new chain segments & OK/BK
-function gh0 { [[ -f $p5 ]] || return;tail -n${1:-$hors} $p5;[[ $1 ]] && return;gl0;nex "$m\n";sso GETH $n0;cpe; }                                            # geth historic report
+function gh0 { [[ -f $p5 ]] || return;tail -n${1:-$hors} $p5;[[ $1 ]] && return;gl0;swn "$m\n";sso GETH $n0;cpe; }                                            # geth historic report
 function gl0 {                                                                                                                                                # geth report
   dts;ok=OK;if [[ $(sst $n0 running) ]];then local e=$(gy);gb;gv;gq;m="$(dnn) sgs: $(printf '%4i' $g0)"
     if [[ $(echo $e|grep false) ]];then m="GETH $ok SYC $m";else m="GETH $ok NSY $m blocks: $(($(gi $e)-$(gc $e)))";fi                                        # OK SYC/NSY (dnn) sgs: 5 blocks: 8 (6)
@@ -53,8 +53,8 @@ function gl0 {                                                                  
 }
 function glt { tail -n$1 $p5 2>$s3|cut -d' ' -f1|sort -u|wc -l; }                                                                                             # get geth restart activity test
 function grt { [[ $(glt 6) -eq 1 ]] && sot 6; }                                                                                                               # 6 hours old system reboot test
-function grb { ok=OK;nex "RSTR SYSTEM $(dnn)" >> $p5;sex reboot; }                                                                                            # geth system reboot
-function grs { gv;snp $n0 $1 10 50;sex "$w3 $n0";sleep 20s;dts;gq;[[ -f $p5 ]] && nex "RSTR SERVIC $(dnn)" >> $p5; }                                          # change/stop/load/start/log geth
+function grb { ok=OK;swn "RSTR SYSTEM $(dnn)" >> $p5;sex reboot; }                                                                                            # geth system reboot
+function grs { gv;snp $n0 $1 10 50;sex "$w3 $n0";sleep 20s;dts;gq;[[ -f $p5 ]] && swn "RSTR SERVIC $(dnn)" >> $p5; }                                          # change/stop/load/start/log geth
 # beacon control commands
 function bz  { echo $((10*(5*zk+2*zz+zx+zw)))                                       ; }                                                                       # get numerator paid errors
 function bw  { echo $((10*z1))                                                      ; }                                                                       # get numerator processed blocks
@@ -150,12 +150,12 @@ function bon { [[ -f $p2 ]] || return;nn=$(pt2 $1 $(bv));l2=$(bff 23:58);bo7 $nn
 function boa { local g=${1:-$bpri};echo "BO$(printf '%5i' $(bo7 $g|wc -l)) $(printf '%3i' $g)";bo7 $g;((g<bprf)) && boa $((g+bprs)); }                        # recursively show homologous nodes report
 function bh0 {
   [[ -f $p2 ]] || return;tail -n${1:-$hors} $p2;[[ $1 ]] && return                                                                                            # last beacon            report
-  boi;nex "BO$(printf '%5i' $(echo "$l2"|wc -l)) $(printf '%3i' $b2)$(printf '%91s')x5 x2  x1 x1";bo6                                                         # homologous             report
-  bl0;nex "BL$(printf '%9i' $(bbl))\n$m";bm0                                                                                                                  # current beacon         report
-  bmo;nex "BM$(printf '%9i' $(bml))$(printf '%46s')i20  i30  i40  i50  i60  i70  i80\n$m";sso BEAC $n1;sso VALI $n3;cpe                                       # medias/services/system report
+  boi;swn "BO$(printf '%5i' $(echo "$l2"|wc -l)) $(printf '%3i' $b2)$(printf '%91s')x5 x2  x1 x1";bo6                                                         # homologous             report
+  bl0;swn "BL$(printf '%9i' $(bbl))\n$m";bm0                                                                                                                  # current beacon         report
+  bmo;swn "BM$(printf '%9i' $(bml))$(printf '%46s')i20  i30  i40  i50  i60  i70  i80\n$m";sso BEAC $n1;sso VALI $n3;cpe                                       # medias/services/system report
 }
 function brb { if srt;then echo RB;else echo $1;fi; }                                                                                                         # get reboot/other tag
-function bro { dts;bb;bnn $(fs4 peers:);[[ -f $p2 ]] && nex "$(printf 'R%03i' $1) ${2:-$ok} $(printf '%3i' $(bu)) $(dnn)" >> $p2; }                           # log restart info
+function bro { dts;bb;bnn $(fs4 peers:);[[ -f $p2 ]] && swn "$(printf 'R%03i' $1) ${2:-$ok} $(printf '%3i' $(bu)) $(dnn)" >> $p2; }                           # log restart info
 function bpt { [[ $(date +%s) -ge $(bss $1 6) ]]; }                                                                                                           # ideal position test (based on time)
 function btg { echo $(date -d@${1:-0} +%M:%S|tr -d :)t$(date -d@$(($(date +%s)+${1:-0})) +%H:%M:%S|tr -d :); }                                                # get end file sleep tag
 function bss { echo $((${2:-0}+$(date -d$(bf1 $1) +%s))); }                                                                                                   # get sum secounds + time
@@ -197,12 +197,12 @@ function brl {                                                                  
       else
         m="${v[0]} $ok $(printf '%3i' ${v[2]}) $(dnn)"                                                                                                        # restart lines
       fi
-    fi                                                                                           ;nex "$m" >> ${p2}r                                          # new beacon output
+    fi                                                                                           ;swn "$m" >> ${p2}r                                          # new beacon output
   done <<< $(cat $p2)
   [[ -f $p3 ]] || return;rm -f ${p3}r;bmi;local d=0000-00-00;local l=0;local n=0;local h=0;local g=0;while read -a o;do
     d=${o[3]};h=$g;g=$(grep -n "$d 23:58" ${p2}r|cut -d: -f1);[[ ${g:=$h} -le $h ]] && continue;dts $d\ ${o[4]};nn=${o[5]:4:2}                                # get next beacon log position
     nr=${o[6]};nm=${o[13]};nd=${o[14]};l2=$(brh $g|bfl 23:58);bo2 $d;((l+=b2));((n+=1));b3=$(nu5 $l/$n)                                                       # cur/avg homologous position
-    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${o[15]};b5=${o[12]};b7=${o[11]};bms;nex "$m" >> ${p3}r                                          # sum err arrays & new medias output
+    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${o[15]};b5=${o[12]};b7=${o[11]};bms;swn "$m" >> ${p3}r                                          # sum err arrays & new medias output
   done <<< $(cat $p3)
 }
 function bsl {                                                                                                                                                # shrink beacon log using barqivo
@@ -217,26 +217,26 @@ function bbt { [[ $(grep $d0 ${p2} 2>$s3|wc -l) -gt 0 ]]; }                     
 function bct { local n=$((nn-5));[[ $nm -ge $n && $(bl6 $hors) -eq 1 ]] && ( btt || sot ); }                                                                  # change configured peers test
 function bdl { local d=$(pt0 $1 sai);[[ -f $p2 && $d != sai ]] || return;cp $p2 ${p2}o;grep -v $d ${p2}o > $p2;grep $d ${p2}o > ${p2}d; }                     # delete beacon log day
 function nsh {
-  nex "ROUTES\t\t$(ip route show|grep 'default via'|grep -v linkdown|cut -d' ' -f3)\nDNS\t\t$(resolvectl|grep 'Current DNS'|cut -d' ' -f6)"                   # routes
-  local v=0;for v in $(ip a|grep 'state UP'|cut -d: -f2);do nex "$v\t\t$(resolvectl dns|grep $v|cut -d' ' -f4-6)";done                                        # dns info
+  swn "ROUTES\t\t$(ip route show|grep 'default via'|grep -v linkdown|cut -d' ' -f3)\nDNS\t\t$(resolvectl|grep 'Current DNS'|cut -d' ' -f6)"                   # routes
+  local v=0;for v in $(ip a|grep 'state UP'|cut -d: -f2);do swn "$v\t\t$(resolvectl dns|grep $v|cut -d' ' -f4-6)";done                                        # dns info
 }
 function cpe {                                                                                                                                                # system status
   local e='NO';[[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK';dts
-  m=$(ss2 systemd-timesyncd);[[ $(echo $m|grep dead) ]] && m=$(ss2 ntp);nex "CLCK $e $(printf '%3i' $(fs0 clock|wc -l)) $dt status: $m"                       # CLCK info
+  m=$(ss2 systemd-timesyncd);[[ $(echo $m|grep dead) ]] && m=$(ss2 ntp);swn "CLCK $e $(printf '%3i' $(fs0 clock|wc -l)) $dt status: $m"                       # CLCK info
   [[ $1 = c ]] && return;local l=0;local n=0;local v=0
   local d=$(fs3|grep throttled|head -n1|sed 's%.* \([0-9]*:[0-9]*\):[0-9]*.*%\1%')
   local e=$(fs3|grep normal   |tail -n1|sed 's%.* \([0-9]*:[0-9]*\):[0-9]*.*%\1%')
   local v=0;for v in $(sensors 2>$s3|grep 'Package\|Core'|sed 's%.*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\1%');do ((n+=1));l=$(nu1 $l$v 1);done
-  [[ $d ]] && d="throttled: $d";[[ $e ]] && e="normal: $e";nex "TEMP $(nu5 $l/$((n==0?1:n)) 1 2 %5.1fC) $dt $d $e"                                            # TEMP cpu info
+  [[ $d ]] && d="throttled: $d";[[ $e ]] && e="normal: $e";swn "TEMP $(nu5 $l/$((n==0?1:n)) 1 2 %5.1fC) $dt $d $e"                                            # TEMP cpu info
   [[ $1 = p ]] && return
   m="INFO$(printf '%3i' $(fs6)) $(printf '%3i' $(fs5)) $dt"                                                                                                   # usb/cpu erros count
   m="$m uptime:$(uptime|sed 's%[0-9]*:[0-9]*:[0-9]*%%;s%[0-9]*:[0-9]*,%%;s%[0-9]* users*,%%;s% average\([^,]*\).*%\1%;s%  *% %g')"                            # uptime/load info
-  if [[ $(cat $s6) -eq 0 ]];then e=off;else e=on;fi;if [[ $(cat $s7) -eq 1 ]];then d=off;else d=on;fi;nex "$m, usb $e, turbo $d"                              # usb/turbo info
+  if [[ $(cat $s6) -eq 0 ]];then e=off;else e=on;fi;if [[ $(cat $s7) -eq 1 ]];then d=off;else d=on;fi;swn "$m, usb $e, turbo $d"                              # usb/turbo info
   local l=$(fs2|grep -i 'error' |wc -l);local n=$(fs1|grep -v ' INFO '|wc -l)
   local e=$(fs2|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'                                |cut -c1-53)
   local d=$(fs1|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
-  m="ERRO$(printf '%3i' $l) $(printf '%3i' $n) $dt";[[ $l -gt 0 ]] && m="$m system: $e";[[ $n -gt 0 ]] && m="$m ethrum: $d";(( l+n )) && nex "$m"             # sys/eth errors info
-  m='';srt && m="$m, reboot $(($(sra)/60/60)) hours ago";[[ $(bsc) -gt 0 ]] && m="$m, committee on";[[ $m ]] && nex "INFO        $dt${m#*,}"                  # reboot/committee info
+  m="ERRO$(printf '%3i' $l) $(printf '%3i' $n) $dt";[[ $l -gt 0 ]] && m="$m system: $e";[[ $n -gt 0 ]] && m="$m ethrum: $d";(( l+n )) && swn "$m"             # sys/eth errors info
+  m='';srt && m="$m, reboot $(($(sra)/60/60)) hours ago";[[ $(bsc) -gt 0 ]] && m="$m, committee on";[[ $m ]] && swn "INFO        $dt${m#*,}"                  # reboot/committee info
 }
 # Plex Media Server
 function xop { uf5 32400     ;uf1 32400 192.168.8.0/24 plex; }
@@ -301,7 +301,7 @@ function wa  {
   if [[ $(pex 'ufw status'|grep -i inactive) ]];then
     yex 'ufw enable'                                                                                                                                          # enable asks: Proceed with operation (y|n)?
   else
-    uex 'FIREWALL ALREADY ACTIVE'
+    swu 'FIREWALL ALREADY ACTIVE'
   fi
 }
 # para/disable goethereum/beacon/validator/prometheus/grafana
@@ -319,14 +319,14 @@ function nd  { [[ $(sst $n5 loaded) ]] && { cex "$w5 $n5"; } }
 function fd  { [[ $(sst $n6 loaded) ]] && { cex "$w5 $n6";uf3 3000/tcp;sex 'ufw reload'; } }
 function dpa { cex "$w2 $o2";sex "$w2 systemd-resolved";cex "$w3 $o2";sex "$w3 systemd-resolved"; }                                                           # DNS stop/start
 function ssp {
-  uex 'QUER MESMO TRANSFERIR VALIDATORS?';read rsp
+  swu 'QUER MESMO TRANSFERIR VALIDATORS?';read rsp
   if [[ $rsp = sim && ! -f $p1/vc_slash && ! -f $p1/vc_lock && -f $p1/vc_keys ]];then
     vp;vd
-    uex 'SAVE SLASHING PROTECTION DB'
+    swu 'SAVE SLASHING PROTECTION DB'
     sex "cp $p8/slashing_protection.sqlite $p0"
     sex "chown eth:eth $p0/slashing_protection.sqlite"
     scp $p0/slashing_protection.sqlite $2:~
-    uex 'SAVED SLASHING PROTECTION DB IN $2'
+    swu 'SAVED SLASHING PROTECTION DB IN $2'
   fi
 }
 function umt { [[ $(cat $s6) -eq 1 && $(fs6) -gt 10 ]]; }                                                                                                     # usb messages test
@@ -346,6 +346,7 @@ function sr9 { chmod 644 $1.jwt;sex "mv $1.jwt $s4/$1.jwt"; }
 
 [[ $1 = jwt ]] && { [[ -d $p9/geth ]] && jw0;[[ -d $p7 && -f jwt ]] && jw1 eth2 $p7;[[ -f jwt ]] && sex "rm jwt"; }
 [[ $1 = srv ]] && { [[ -f $s4/$n0.service ]] && sr0;[[ -f $s4/$n1.service ]] && sr1;[[ -f $s4/$n3.service ]] && sr3; }
+[[ $1 = chk ]] && { cex 'chkrootkit'; }
 [[ $1 = eip ]] && { curl -s4 "https://${3:-meo.fruga.pt}:$2@dyn.dns.he.net/nic/update?hostname=${3:-meo.fruga.pt}" &>$s3; }
 [[ $1 = dsh ]] && { resolvectl query ${2:-smtp.gmail.com}; }
 [[ $1 = drs ]] && { dpa; }
@@ -353,17 +354,17 @@ function sr9 { chmod 644 $1.jwt;sex "mv $1.jwt $s4/$1.jwt"; }
 [[ $1 = nsh ]] && { nsh; }
 [[ $1 = trs ]] && { [[ $(sst systemd-timesyncd masked) ]] || cex "$w0 restart systemd-timesyncd";cpe c; }
 [[ $1 = vcp ]] && { [[ $2 ]] && ssp $2; }
-[[ $1 = gl  ]] && { gl0;nex "$m"; }
-[[ $1 = glf ]] && { gl0;nex "$m" >> $p5;grt && grb;[[ $ok != OK ]] && grs 0;pas; }                                                                            # geth log/reboot/restart & parameter set
-[[ $1 = bl  ]] && { bl0;nex "$m"; }
-[[ $1 = bm  ]] && { bm0;bmo;nex "$m"; }
-[[ $1 = bn  ]] && { bm0;bno;nex "$m"; }
-[[ $1 = blf ]] && { bl0;nex "$m" >> $p2;stt && bo5 && bht && bst && bdl $d0;[[ $ok != OK ]] && b1r 0;pas; }                                                   # beacon log/delete day/restart & parameter set
-[[ $1 = bmf ]] && { bm0;bms;bbt && nex "$m" >> $p3;bct && b1r $b4 $(brb PE) 120; }
-[[ $1 = bnf ]] && { bm0;bno;nex "$m" >> $p6; }
+[[ $1 = gl  ]] && { gl0;swn "$m"; }
+[[ $1 = glf ]] && { gl0;swn "$m" >> $p5;grt && grb;[[ $ok != OK ]] && grs 0;pas; }                                                                            # geth log/reboot/restart & parameter set
+[[ $1 = bl  ]] && { bl0;swn "$m"; }
+[[ $1 = bm  ]] && { bm0;bmo;swn "$m"; }
+[[ $1 = bn  ]] && { bm0;bno;swn "$m"; }
+[[ $1 = blf ]] && { bl0;swn "$m" >> $p2;stt && bo5 && bht && bst && bdl $d0;[[ $ok != OK ]] && b1r 0;pas; }                                                   # beacon log/delete day/restart & parameter set
+[[ $1 = bmf ]] && { bm0;bms;bbt && swn "$m" >> $p3;bct && b1r $b4 $(brb PE) 120; }
+[[ $1 = bnf ]] && { bm0;bno;swn "$m" >> $p6; }
 [[ $1 = gh  ]] && { gh0 $2; }
 [[ $1 = bh  ]] && { bh0 $2; }
-[[ $1 = bhs ]] && { bm0;bms;[[ -f $p2 ]] && nex "$m";sso BEAC $n1;[[ $(sst $n3 loaded) ]] && sso VALI $n3;cpe; }                                              # lighthouse services & system report
+[[ $1 = bhs ]] && { bm0;bms;[[ -f $p2 ]] && swn "$m";sso BEAC $n1;[[ $(sst $n3 loaded) ]] && sso VALI $n3;cpe; }                                              # lighthouse services & system report
 [[ $1 = ghs ]] && { sso GETH $n0;cpe; }                                                                                                                       # geth service & system report
 [[ $1 = bo  ]] && { bo0 $2 $3 $4; }
 [[ $1 = bon ]] && { bon $2; }
@@ -519,5 +520,6 @@ if [[ ! $1 ]];then
   m="$m\nnrs\t\tdns/netplan reset"
   m="$m\ndrs\t\tdns reset"
   m="$m\ntrs\t\ttime sync restart"
-  nex "\n$m\n"
+  m="$m\nchk\t\tcheck server with chkrootkit"
+  swn "\n$m\n"
 fi
