vars-cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -110,10 +110,10 @@ function blo {
 }
 function bcc { if bct       ;then echo c;else echo _;fi; }                                                                                                    # get change configured peers char
 function bdc { if bht && bst;then echo d;else echo _;fi; }                                                                                                    # get delete cc log day       char
-function bmi { zk=0;zz=0;zx=0;unset o;o[1]=0;unset k;k[0]=0;unset z;z[0]=0;unset x;x[0]=0;unset w;w[0]=0;unset c;c[0]=0;unset a;a[0]=0;bm6; }                 # ini err/cnt/avg penalty arrays
+function bmi { zk=0;zz=0;zx=0;unset v;v[1]=0;unset k;k[0]=0;unset z;z[0]=0;unset x;x[0]=0;unset w;w[0]=0;unset c;c[0]=0;unset a;a[0]=0;bm6; }                 # ini err/cnt/avg penalty arrays
 function bm0 {                                                                                                                                                # cc-daily report
   [[ -f ${p[11]} ]] || return;bmi;b4=0;b5=$(fs0 reduce|wc -l);dts;nn=$(bv);bnn $(fs4 peers:);bl2;[[ -f ${p[14]} ]] && bm4                                     # ini vars/arrays
-  l3=$(tail -n$(($(bbl)-o[1])) ${p[11]} 2>${p[3]}|bfl);[[ $l3 ]] && bm1;bm2;bo4;bm5 ${a[$nn]};b7="rm$(bdc)$(bcc)$(date +%w)_peers:"                           # add cc lines & homologous/avg position
+  l3=$(tail -n$(($(bbl)-v[1])) ${p[11]} 2>${p[3]}|bfl);[[ $l3 ]] && bm1;bm2;bo4;bm5 ${a[$nn]};b7="rm$(bdc)$(bcc)$(date +%w)_peers:"                           # add cc lines & homologous/avg position
 }
 function bm1 {
   local g=${1:-$bpri};l1=$(echo "$l3"|sed -nEe "s%.+node$g:.+err: +([0-9]+) +([0-9]+) +([0-9]+) +([0-9]+).+%\1\t\2\t\3\t\4%p")                                # set paid errors for current array
@@ -121,7 +121,7 @@ function bm1 {
 }
 function bm2 { k[0]=$(($(bnk)));z[0]=$(($(bnz)));x[0]=$(($(bnx)));w[0]=$(($(bnw)));c[0]=$(($(bnc)));a[0]=$(bm3 0);bm7; }                                      # tot err/cnt/penalty arrays
 function bm3 { nu4 ${k[$1]} ${z[$1]} ${x[$1]} ${w[$1]} ${c[$1]} ; }                                                                                           # get penalty from paid err arrays
-function bm4 { unset o;read -a o <<< $(tail -n1 ${p[14]});bmk;bmz;bmx;bmw;bmc; }                                                                              # set err/cnt penalty arrays from barqivo
+function bm4 { read -a v <<< $(tail -n1 ${p[14]});bmk;bmz;bmx;bmw;bmc; }                                                                              # set err/cnt penalty arrays from barqivo
 function bm5 { local g=${2:-$bpri};local n=$1;if ((a[g]<n));then b4=$((g-nn));n=${a[$g]};fi;((g<bprf)) && bm5 $n $((g+bprs)); }                               # set recursively peer change <- min penalties
 function bm6 { local g=${1:-$bpri};k[$g]=0;z[$g]=0;x[$g]=0;w[$g]=0;c[$g]=0;a[$g]=0         ;((g<bprf)) && bm6    $((g+bprs)); }                               # ini recursively penalty arrays
 function bm7 { local g=${1:-$bpri};a[$g]=$(bm3 $g)                                         ;((g<bprf)) && bm7    $((g+bprs)); }                               # avg recursively penalty arrays
@@ -130,11 +130,11 @@ function bkm { local g=${1:-$bpri};((k[g]+=$((0$(printf '+%i' $(echo "$l1"|cut -
 function bzm { local g=${1:-$bpri};((z[g]+=$((0$(printf '+%i' $(echo "$l1"|cut -f2)))))); }                                                                   # sum failed target err array
 function bxm { local g=${1:-$bpri};((x[g]+=$((0$(printf '+%i' $(echo "$l1"|cut -f3)))))); }                                                                   # sum failed head   err array
 function bwm { local g=${1:-$bpri};((w[g]+=$((0$(printf '+%i' $(echo "$l1"|cut -f4)))))); }                                                                   # sum delay         err array
-function bmc { local g=${1:-$bpri};local n=${2:-5 };c[$g]=${o[$n]};((g<bprf)) && bmc $((g+bprs)) $((n+1)); }                                                  # set recursively               cnt array
-function bmk { local g=${1:-$bpri};local n=${2:-13};k[$g]=${o[$n]};((g<bprf)) && bmk $((g+bprs)) $((n+1)); }                                                  # set recursively missing       err array
-function bmz { local g=${1:-$bpri};local n=${2:-21};z[$g]=${o[$n]};((g<bprf)) && bmz $((g+bprs)) $((n+1)); }                                                  # set recursively failed target err array
-function bmx { local g=${1:-$bpri};local n=${2:-29};x[$g]=${o[$n]};((g<bprf)) && bmx $((g+bprs)) $((n+1)); }                                                  # set recursively failed head   err array
-function bmw { local g=${1:-$bpri};local n=${2:-37};w[$g]=${o[$n]};((g<bprf)) && bmw $((g+bprs)) $((n+1)); }                                                  # set recursively delay         err array
+function bmc { local g=${1:-$bpri};local n=${2:-5 };c[$g]=${v[$n]};((g<bprf)) && bmc $((g+bprs)) $((n+1)); }                                                  # set recursively               cnt array
+function bmk { local g=${1:-$bpri};local n=${2:-13};k[$g]=${v[$n]};((g<bprf)) && bmk $((g+bprs)) $((n+1)); }                                                  # set recursively missing       err array
+function bmz { local g=${1:-$bpri};local n=${2:-21};z[$g]=${v[$n]};((g<bprf)) && bmz $((g+bprs)) $((n+1)); }                                                  # set recursively failed target err array
+function bmx { local g=${1:-$bpri};local n=${2:-29};x[$g]=${v[$n]};((g<bprf)) && bmx $((g+bprs)) $((n+1)); }                                                  # set recursively failed head   err array
+function bmw { local g=${1:-$bpri};local n=${2:-37};w[$g]=${v[$n]};((g<bprf)) && bmw $((g+bprs)) $((n+1)); }                                                  # set recursively delay         err array
 function bma { local g=${2:-$bpri};if ((g<=bprf));then bma "$1 $(printf '%4i' ${a[$g]})" $((g+bprs));else echo "$1";fi; }                                     # sum recursively penalty       avg array
 function bnc { local g=${3:-$bpri};if ((g<=bprf));then bnc "${1:-0}${2:-+}${c[$g]}" "$2" $((g+bprs));else echo "$1";fi; }                                     # sum recursively               cnt array
 function bnk { local g=${3:-$bpri};if ((g<=bprf));then bnk "${1:-0}${2:-+}${k[$g]}" "$2" $((g+bprs));else echo "$1";fi; }                                     # sum recursively missing       err array
@@ -211,10 +211,10 @@ function brl {                                                                  
       fi
     fi                                                                                           ;swn "$m" >> ${p[11]}r                                       # new cc output
   done <<< $(cat ${p[11]})
-  [[ -f ${p[12]} ]] || return;rm -f ${p[12]}r;bmi;local d=0000-00-00;local l=0;local n=0;local h=0;local g=0;unset o;while read -a o;do
-    d=${o[3]};h=$g;g=$(grep -n "$d 23:58" ${p[11]}r|cut -d: -f1);[[ ${g:=$h} -le $h ]] && continue;dts $d\ ${o[4]};nn=${o[5]:4:2}                             # get next cc log position
-    nr=${o[6]};nm=${o[13]};nd=${o[14]};l2=$(brh $g|bfl 23:58);bo2 $d;((l+=b2));((n+=1));b3=$(nu5 $l/$n)                                                       # cur/avg homologous position
-    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${o[15]};b5=${o[12]};b7=${o[11]};bms;swn "$m" >> ${p[12]}r                                       # sum err arrays & new cc-daily output
+  [[ -f ${p[12]} ]] || return;rm -f ${p[12]}r;bmi;local d=0000-00-00;local l=0;local n=0;local h=0;local g=0;while read -a v;do
+    d=${v[3]};h=$g;g=$(grep -n "$d 23:58" ${p[11]}r|cut -d: -f1);[[ ${g:=$h} -le $h ]] && continue;dts $d\ ${v[4]};nn=${v[5]:4:2}                             # get next cc log position
+    nr=${v[6]};nm=${v[13]};nd=${v[14]};l2=$(brh $g|bfl 23:58);bo2 $d;((l+=b2));((n+=1));b3=$(nu5 $l/$n)                                                       # cur/avg homologous position
+    l3=$(brh $g|tail -n$((g-h))|bfl);[[ $l3 ]] && bm1;bm2;b4=${v[15]};b5=${v[12]};b7=${v[11]};bms;swn "$m" >> ${p[12]}r                                       # sum err arrays & new cc-daily output
   done <<< $(cat ${p[12]})
 }
 function bsl {                                                                                                                                                # shrink cc      log using barqivo
@@ -233,10 +233,10 @@ function wst { echo $@|sed 's%[^: ]*: *%%g;s%,[^,]*(routed)%%;s% (incoming),% <<
 function cpe {                                                                                                                                                # system status
   local e='NO';[[ $(${p[67]}|sed -n 's%.*synchronized: \([a-z]*\) *%\1%p') = yes ]] && e='OK';dts
   if [[ $(sst ${p[77]} masked) ]];then m=$(ss3 ntp);else m=$(ss3 ${p[77]});fi;swn "CLCK $e $(printf '%3i' $(fs0 clock|wc -l)) $dt status: $m"                 # CLCK info
-  [[ $1 = c ]] && return;local l=0;local n=0;local v=0
+  [[ $1 = c ]] && return;local l=0;local n=0;local g=0
   local d=$(fs3|grep throttled|head -n1|sed 's%.* \([0-9]*:[0-9]*\):[0-9]*.*%\1%')
   local e=$(fs3|grep normal   |tail -n1|sed 's%.* \([0-9]*:[0-9]*\):[0-9]*.*%\1%')
-  local v=0;for v in $(sensors 2>${p[3]}|sed -n "s%\(${p[51]}\).*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\2%p");do ((n+=1));l=$(nu1 $l$v 1);done
+  local g=0;for g in $(sensors 2>${p[3]}|sed -n "s%\(${p[51]}\).*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\2%p");do ((n+=1));l=$(nu1 $l$g 1);done
   [[ $d ]] && d="throttled: $d";[[ $e ]] && e="normal: $e";swn "TEMP $(nu5 $l/$((n==0?1:n)) 1 2 %5.1fC) $dt $d $e"                                            # TEMP cpu info
   [[ $1 = p ]] && return
   if [[ $(cat ${p[6]}) -eq 0 ]];then e=off;else e=on;fi;if [[ $(cat ${p[7]}) -eq 1 ]];then d=off;else d=on;fi                                                 # usb/cpu current state
