cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -23,22 +23,23 @@ function bz  { echo $((10*(9*zk+3*zz+zx+zw)))                                   
 function bw  { echo $((10*z1))                                                      ; }                                                                       # get numerator processed blocks
 function bf  { echo $((90*z3))                                                      ; }                                                                       # get numerator general errors
 function bu  { echo $(((z5>200?$(bz)/z5:0)+(z2>300?$(bw)/z2:0)+(z4>999?$(bf)/z4:0))); }                                                                       # get restart idx
+function bi  { echo $((nd+zk*100+zz*10))                                            ; }                                                                       # get delete day idx
 function bs  { tail -n$1 $p2 2>$s3|cut -d' ' -f1|sort -u|wc -l; }                                                                                             # get restart activity test
 function bk  { cat       $p2 2>$s3                      |wc -l; }                                                                                             # get beacon line count
 function bv  { nn=$(nu0 $(rd1 $ethb target-peers [0-9])); }                                                                                                   # set configured peers
-function bb  { l0=$(fs0 $bpid] 3600);bl1;[[ (1 -eq $(bs $hors) && $(bu) -ge 1) || (1 -eq $(bs 5) && $(bu) -ge 5) ]] && ok=BK; }                               # set ok (OK/BK)
+function bb  { l0=$(fs0 $bpid] 3600);bl1;bl2;[[ (1 -eq $(bs $hors) && $(bu) -ge 1) || (1 -eq $(bs 5) && $(bu) -ge 5) ]] && ok=BK; }                           # set ok (OK/BK)
 function bfl { cat $2|grep "BEAC.*$1"; }                                                                                                                      # filter beacon lines
-function bl  { dts;if [[ $(rd0 $ethb running) ]];then bl2;bv;bnn $(fs6 peers:);bb;blo;else m=" NOT RUNNING $dt";fi; }                                         # beacon report
-function bl0 { fs0 "attestation(s).*$1"|bl3; }                                                                                                                # get number of paid activities
+function bl  { dts;if [[ $(rd0 $ethb running) ]];then bl3;bv;bnn $(fs6 peers:);bb;blo;else m=" NOT RUNNING $dt";fi; }                                         # beacon report
+function bl0 { fs0 "attestation(s).*$1"|bl5; }                                                                                                                # get number of paid activities
 function bl1 {                                                                                                                                                # set restart idx vars
   z1=${1:-$(echo "$l0"|grep 'rocessed block'|wc -l)};z2=${2:-$(echo "$l0"|grep 'block received'|wc -l)}                                                       # set processed/received blocks
   z3=${3:-$(echo "$l0"|grep -v ' INFO '     |wc -l)};z4=${4:-$(echo "$l0"|grep    ' INFO '     |wc -l)}                                                       # set error/info         lines
-  z5=${5:-$(bl0 success)};zk=${6:-$(bl0 missing)};zz=${7:-$(bl0 target)};zx=${8:-$(bl0 head)};zw=${9:-$(bl0 had)};ok=${10:-OK}                                # set success/erros      activities
+  z5=${5:-$(bl0 success)};zx=${6:-$(bl0 head)};zw=${7:-$(bl0 had)};ok=${8:-OK}                                                                                # set success/head/had activities
 }
-function bl2 { b0=${1:-$(fs0 'published block'|wc -l)};b1=${2:-$(nu5 $(fs6 delay_ms:))}; }                                                                    # set published blocks/avg delays
-function bl3 { sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w; }                                                                                               # get number of validators
-function bl4 { echo $H|sudo -S egrep "attestation\(s\).+(missing|target|head).+validators: +\[(\"[0-9]+\", +){17}\"[0-9]+\"\]" $s1 2>$s3|bl3; }               # get irrelevant paid activities
-#function bl5 { local n=$(bl4);((n>0&&n%18==0)) && { ((zk-=n/3)); ((zz-=n/3)); ((zx-=n/3)); } }                                                               # del irrelevant paid activities
+function bl2 { zk=${1:-$(bl0 missing)};zz=${2:-$(bl0 target)}; }                                                                                              # set missing/target activities
+function bl3 { b0=${1:-$(fs0 'published block'|wc -l)};b1=${2:-$(nu5 $(fs6 delay_ms:))}; }                                                                    # set published blocks/avg delays
+function bl4 { echo $H|sudo -S egrep "attestation\(s\).+(missing|target|head).+validators: +\[(\"[0-9]+\", +){17}\"[0-9]+\"\]" $s1 2>$s3|bl5; }               # get irrelevant paid activities
+function bl5 { sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w; }                                                                                               # get number of validators
 #    0  1   2          3     4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18 19  20  21  22   23   24     25  26
 # BEAC OK   0 2022-01-03 19:58 node50: 55 reward_penalty: 257 2.23 attestation_block: 3384 1310 0 erros: 0  7  93 17  0 581   0   8 3592  720 delay: 428
 function blo {
@@ -48,11 +49,11 @@ function blo {
   m="$m delay: $(printf '%3i' $b1)"
 }
 function bm  {                                                                                                                                                # bmedias report
-  bm0;b4=0;b5=$(fs0 reduce|wc -l);dts;bv;bnn $(fs6 peers:);[[ -f $p6 ]] && bm4                                                                                # ini vars/arrays
+  bm0;b4=0;b5=$(fs0 reduce|wc -l);dts;bv;bnn $(fs6 peers:);bl2;[[ -f $p6 ]] && bm4                                                                            # ini vars/arrays
   l3=$(tail -n$(($(bk)-o[1])) $p2 2>$s3|bfl);[[ $l3 ]] && bm1 20;bm2;[[ ${b2:-0} -eq 0 ]] && bo0                                                              # add beacon lines & homologous position
   b3=$(nu5 $b2 $(fs5 '\w* *\w*' $p3));bm5 20 ${a[$nn]};[[ $b2 -le $b3 || $(bs $hors) -gt 1 ]] && b4=0;bmo;bno                                                 # change configured peers & outputs
 }
-function bm0 { unset o;o[1]=0;unset k;k[0]=0;unset z;z[0]=0;unset x;x[0]=0;unset w;w[0]=0;unset c;c[0]=0;unset a;a[0]=0;bm6 20; }                             # ini err/cnt/avg penalty arrays
+function bm0 { zk=0;zz=0;zx=0;zw=0;unset o;o[1]=0;unset k;k[0]=0;unset z;z[0]=0;unset x;x[0]=0;unset w;w[0]=0;unset c;c[0]=0;unset a;a[0]=0;bm6 20; }         # ini err/cnt/avg penalty arrays
 function bm1 {
   l1=$(echo "$l3"|grep "node$1:"|sed -Ee 's%.+erros: +([0-9]+) +([0-9]+) +([0-9]+) +([0-9]+).+%\1\t\2\t\3\t\4%')                                              # set paid errors for current array
   [[ $l1 ]] && { bkm $1;bzm $1;bxm $1;bwm $1;bcm $1; };[[ $1 -lt 50 ]] && bm1 $(($1+5))                                                                       # recursively sum paid err arrays
@@ -85,7 +86,7 @@ function bnc { if [[ $1 -ge 20 ]];then bnc $(($1-5)) "$2$3${c[$1]}" "$3";else ec
 function bmo {
   m=" $(printf '%2i' $b3) $(printf '%3i' $b2) $(dnn) median_penalty: $(printf '%4.2f' ${a[50]}) $(printf '%4.2f' ${a[45]}) $(printf '%4.2f' ${a[40]})"
   m="$m $(printf '%4.2f' ${a[35]}) $(printf '%4.2f' ${a[30]}) $(printf '%4.2f' ${a[25]}) $(printf '%4.2f' ${a[20]}) all_median: $(printf '%4.2f' ${a[0]})"
-  m="$m crmd_peers: $(printf '%2i' $b4) $(printf '%2i' $b5) $(printf '%2i' $nm) $(printf '%4i' $nd)"
+  m="$m crmd_peers: $(printf '%2i' $b4) $(printf '%2i' $b5) $(printf '%2i' $nm) $(printf '%4i' $(bi))"
 }
 #    0   1          2     3    4 5 6 7 8 9 10 11   12 13 14 15 16 17 18 19   20 21 22 23 24 25 26 27   28 29 30 31 32 33 34 35   36 37 38 39 40 41 42 43
 # BEAC 620 2021-12-09 09:17 cnt: 0 0 0 0 0 11 11 mis: 22 22 22 22 22 22 22 mat: 33 33 33 33 33 33 33 mah: 44 44 44 44 44 44 44 dly: 55 55 55 55 55 55 55
@@ -118,7 +119,7 @@ function brl {                                                                  
   [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p3}new ]] && rm ${p3}new
   unset v;while read -a v;do ok=${v[1]};dts ${v[3]}\ ${v[4]};nn=${v[5]:4:2};nr=${v[6]}                                                                        # uncalculated vars
     if [[ ${v[0]} = BEAC ]];then
-      bl1 ${v[19]} ${v[20]} ${v[22]} ${v[23]} ${v[11]} ${v[15]} ${v[16]} ${v[17]} ${v[18]} ${v[1]};bl2 ${v[13]} ${v[26]};blo                                  #  BEAC lines calculated output
+      bl1 ${v[19]} ${v[20]} ${v[22]} ${v[23]} ${v[11]} ${v[17]} ${v[18]} ${v[1]};bl2 ${v[15]} ${v[16]};bl3 ${v[13]} ${v[26]};blo                              #  BEAC lines calculated output
     else
       m=" $ok $(printf '%3i' ${v[2]}) $(dnn)"                                                                                                                 # !BEAC lines
     fi                                                          ;echo "${v[0]}$m" >> ${p2}new                                                                 # new beacon output
@@ -133,7 +134,7 @@ function bsl {                                                                  
   [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p6}new ]] && rm ${p6}new;tail -n$(($(cat $p2|wc -l)-$(tail -n1 $p6|cut -d' ' -f2))) $p2 > ${p2}new                 # new beacon  log output
   head -n$(($(cat $p6|wc -l)-1)) $p6 > ${p6}new;tail -n1 $p6|sed 's%BEAC [0-9]*%BEAC 0%' >> ${p6}new                                                          # new barqivo log output
 }
-function bdt { local n=$((nd+zk*100+zz*10));if [[ $n -ge 1500 ]];then n=18;else n=$(bl4);fi;((n>0&&n%18==0)) && bdl $d0; }                                    # testa delete beacon log day
+function bdt { local n=$(bi);if [[ $n -ge 1500 ]];then n=18;else n=$(bl4);fi;((n>0&&n%18==0)) && bdl $d0; }                                                   # testa delete beacon log day
 function bdl { local d=$(pt0 $1 sai);[[ $d = sai ]] && return;cp $p2 ${p2}sav;grep -v $d ${p2}sav > $p2; }                                                    #       delete beacon log day
 function bnl {
   [[ -f $p2 && -f ${p2}new && ! -f ${p2}sav ]] && { cp $p2 ${p2}sav;mv ${p2}new $p2; }                                                                        # substitute new beacon  log
