cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -12,6 +12,7 @@ function nu5 { if [[ $3 -gt $1 ]];then echo $(($2/$3))                          
 function nu6 { if [[ $@        ]];then echo $(nu3 $(nu2 $@)/$(echo $@|wc -w) 5 1)                  ;else echo 0;fi; }                             # get average of list of numbers
 function nu7 { if [[ $1 -ne 0  ]];then echo $1                                                     ;else echo 1;fi; }                             # get safe denominator
 function nu8 { nu2 $(echo "$b7"|cut -f$1); }                                                                                                      # get sum specific list of numbers
+function nu9 { echo $1|sed 's%node\([0-9]*\):%\1%'; }                                                                                             # get peers from node tag
 function cex { echo -e "${i}${1^^}${f}";echo $H|sudo -S $1                      2>/dev/null     ; }                                               # superuser-command (visible)
 function sex {                          echo $H|sudo -S $1                      2>/dev/null 1>&2; }                                               # superuser-command (silent)
 function dmr { sex "$sctl daemon-reload"                 ; }                                                                                      # daemon-reload
@@ -53,24 +54,14 @@ function grs { rd4 $ethg $1 $(gv) 10 15;sex "$sctl start $ethg";sleep 20s;echo "
 # beacon control commands
 function bv  { nu0 $(rd1 $ethb target-peers [0-9])                   ; }                                                                          # get configured peers
 function bq  { nu0 $(fs4 peers: 1|sed 's%.*peers: *\([0-9]*\).*%\1%'); }                                                                          # get current    peers
-function bi  { nu4 ${k[$1]} ${z[$1]} ${x[$1]} ${w[$1]} ${c[$1]}      ; }                                                                          # get avg penalty from paid err arrays
-function bx  { echo $1|sed 's%node\([0-9]*\):%\1%'                                     ; }                                                        # get peers from node tag
+function bi  { nu4 ${k[$1]} ${z[$1]} ${x[$1]} ${w[$1]} ${c[$1]}                        ; }                                                        # get avg penalty from paid err arrays
 function bz  { echo $((10*(9*zk+3*zz+zx+zw)))                                          ; }                                                        # get numerator paid errors
 function bw  { echo $((10*z1))                                                         ; }                                                        # get numerator processed blocks
 function br  { echo $((90*z3))                                                         ; }                                                        # get numerator general errors
 function bu  { echo $(($(nu5 200 $(bz) $z5)+$(nu5 100 $(bw) $z2)+$(nu5 100 $(br) $z4))); }                                                        # get restart idx
-function bs  { tail -n$1 $p2 2>/dev/null|cut -d' ' -f1|sort -u|wc -l                   ; }                                                        # get restart activity test
-function bk  { cat       $p2 2>/dev/null                      |wc -l                   ; }                                                        # get beacon line count
-function bf  { sort -k10.1n                                                            ; }                                                        # srt beacon lines by penalty
-function bt  { echo "$b1"|bf|grep -n $1|cut -d: -f1                                    ; }                                                        # get homologous beacon lines position
-function bo  { echo "$b1"|wc -l                                                        ; }                                                        # get homologous beacon lines count
-function by  { fs4 "attestation(s).*$1"|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w  ; }                                                        # get paid activities
-function bb  { b9=$(fs4 $bpid] 3600);bn;local g=$(bu);[[ ($g -ge 1 && $(bs $hors) -eq 1) || ($g -ge $l2rs && $(bs $l2rs) -eq 1) ]] && ok=BK; }    # set restart idx vars/OK/BK
-function bn  {
-  z1=${1:-$(echo "$b9"|grep 'rocessed block'|wc -l)};z2=${2:-$(echo "$b9"|grep 'block received'|wc -l)}                                           # set processed blocks (restart idx)
-  z3=${3:-$(echo "$b9"|grep -v ' INFO '     |wc -l)};z4=${4:-$(echo "$b9"|grep ' INFO '        |wc -l)}                                           # set general errors   (restart idx)
-  z5=${5:-$(by success)};zk=${6:-$(by missing)};zz=${7:-$(by target)};zx=${8:-$(by head)};zw=${9:-$(by had)};ok=${10:-OK}                         # set paid activities & OK/BK
-}
+function bs  { tail -n$1 $p2 2>/dev/null|cut -d' ' -f1|sort -u|wc -l; }                                                                           # get restart activity test
+function bk  { cat       $p2 2>/dev/null                      |wc -l; }                                                                           # get beacon line count
+function bb  { b9=$(fs4 $bpid] 3600);bl1;local g=$(bu);[[ ($g -ge 1 && $(bs $hors) -eq 1) || ($g -ge $l2rs && $(bs $l2rs) -eq 1) ]] && ok=BK; }   # set ok (OK/BK)
 function bl  {                                                                                                                                    # beacon report
   if [[ $(rd0 $ethb running) ]];then
     b0=$(fs4 'published block'|wc -l);b5=$(nu6 $(fs4 delay_ms:|sed 's%.*delay_ms: *\([0-9]*\).*%\1%'));dt=$(dts);nn=$(bv);nr=$(bq);bb;blo         # published blocks/avg delays (b0/b5) & get output
@@ -81,28 +72,36 @@ function bl  {                                                                  
 function bm  {                                                                                                                                    # bmedias report
   bm0;b4=0;b8=$(fs4 'reduce peer'|wc -l);dt=$(dts);nn=$(bv);nr=$(bq)                                                                              # ini arrays/vars
   [[ -f $p7         ]] && bm3;b6=$(tail -n$(($(bk)-o[1])) $p2 2>/dev/null|grep BEAC);[[ $b6 ]] && bm1 20;bm2                                      # set arrays from barqivo log & remaining beacon log
-  [[ ${b2:=0} -eq 0 ]] && bo1;b3=$(nu6 $(sed -Ee 's%BEAC +[0-9]+ +([0-9]+).+%\1%' $p3 2>/dev/null))                                               # cur/avg homologous position
+  [[ ${b2:=0} -eq 0 ]] && bo0;b3=$(nu6 $(sed -Ee 's%BEAC +[0-9]+ +([0-9]+).+%\1%' $p3 2>/dev/null))                                               # cur/avg homologous position
   bm5 ${a[$nn]} 20;[[ $(bs $hors) -gt 1 ]] && b4=0;bmo;bno                                                                                        # change configured peers & outputs
 }
 function bh  {                                                                                                                                    # historic report
   [[ ! -f $p2 ]] && return                                                                                                                        # beacon log must exist
-  tail -n${1:-$hors} $p2;[[ $1 ]] && return;bo1;echo -e "BO$(printf '%5i' $(bo)) $(printf '%3i' $b2)";bo2                                         # beacon log/homologous report
+  tail -n${1:-$hors} $p2;[[ $1 ]] && return;bo0;echo -e "BO$(printf '%5i' $(bo2)) $(printf '%3i' $b2)";bo1                                        # beacon log/homologous report
   bl;echo -e "BL$(printf '%9i' $(cat $p2 2>/dev/null|wc -l))\nBEAC$m";bm;echo -e "BM$(printf '%5i' $(cat $p3 2>/dev/null|wc -l))\nBEAC$m"         # beacon/medias report
   sst BEAC $ethb;sst VALI $ethv;cpe                                                                                                               # beacon/validator status & clock/cpu/system/eth info
 }
-function bo1 {                                                                                                                                    # homologous lines/position
+function bl0 { fs4 "attestation(s).*$1"|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w  ; }                                                        # get paid activities
+function bl1 {                                                                                                                                    # set restart idx vars
+  z1=${1:-$(echo "$b9"|grep 'rocessed block'|wc -l)};z2=${2:-$(echo "$b9"|grep 'block received'|wc -l)}                                           # set processed/received blocks
+  z3=${3:-$(echo "$b9"|grep -v ' INFO '     |wc -l)};z4=${4:-$(echo "$b9"|grep ' INFO '        |wc -l)}                                           # set error/info         lines
+  z5=${5:-$(bl0 success)};zk=${6:-$(bl0 missing)};zz=${7:-$(bl0 target)};zx=${8:-$(bl0 head)};zw=${9:-$(bl0 had)};ok=${10:-OK}                    # set success/erros      activities
+}
+function bo0 {                                                                                                                                    # homologous lines/position
   b2=0;[[ ! -f $p2 ]] && return                                                                                                                   # beacon log must exist
   local t=00:00;[[ $(fs2 $1) ]] && b2=$1;[[ $(fs2 $2) ]] && b2=$2;[[ $(fs3 $1) ]] && t=$1;[[ $(fs3 $2) ]] && t=$2                                 # homologous position/time forced
   local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\).*%\1\t\2%')                                               # last yyyy-mm-dd hh:mm beacon log
-  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2);b1=$(grep "BEAC.*$t" $p2);[[ $b2 -eq 0 ]] && b2=$(bt $d)                # set homologous lines/position (b1/b2)
-  local n=0;while [[ ${b2:=0} -eq 0 && $n -lt 50 ]];do ((n+=1));d=$(date -d "$n days ago $t" '+%Y-%m-%d');b2=$(bt $d);done                        # search past homologous info (max 50 days)
+  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2);b1=$(grep "BEAC.*$t" $p2);[[ $b2 -eq 0 ]] && b2=$(bo3 $d)               # set homologous lines/position (b1/b2)
+  local n=0;while [[ ${b2:=0} -eq 0 && $n -lt 50 ]];do ((n+=1));d=$(date -d "$n days ago $t" '+%Y-%m-%d');b2=$(bo3 $d);done                       # search past homologous info (max 50 days)
 }
-function bo2 {                                                                                                                                    # homologous report
+function bo1 {                                                                                                                                    # homologous report
   [[ ! -f $p2 ]] && return;local g=${b2:-0};local d=${b2:-0}                                                                                      # init head/tail lines
-  if [[ $(fs2 $1) ]];then g=$1;else if [[ $g -lt $l2rs && $(bo) -ge $l2rs ]];then d=$l2rs;g=$l2rs;fi;fi                                           # ajust head lines
-  if [[ $(fs2 $1) ]];then d=$1;else if [[ $d -gt $hors                    ]];then d=$hors        ;fi;fi                                           # ajust tail lines
-  echo "$b1"|bf|head -n$g|tail -n$d                                                                                                               # order/filter homologous report
+  if [[ $(fs2 $1) ]];then g=$1;else if [[ $g -lt $l2rs && $(bo2) -ge $l2rs ]];then d=$l2rs;g=$l2rs;fi;fi                                          # ajust head lines
+  if [[ $(fs2 $1) ]];then d=$1;else if [[ $d -gt $hors                     ]];then d=$hors        ;fi;fi;bo4|head -n$g|tail -n$d                  # ajust tail lines & homologous report
 }
+function bo2 { echo "$b1"|wc -l          ; }                                                                                                      # get homologous beacon lines count
+function bo3 { bo4|grep -n $1|cut -d: -f1; }                                                                                                      # get homologous beacon lines position
+function bo4 { echo "$b1"|sort -k10.1n   ; }                                                                                                      # srt beacon lines by penalty
 function blo {
   #    0  1   2          3     4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18     19  20  21   22   23   24         25   26
   # BEAC OK   0 2021-11-22 17:15 node20: 32 reward_penalty: 224 3.54 attestation_block: 2950 2280 0 erros: 2 14 131 29      0 537   0   14 3586 1260     delay: 1000
@@ -146,6 +145,21 @@ function bnx { if [[ $1 -ge 20 ]];then bnx $(($1-5)) "$2$3${x[$1]}" "$3";else ec
 function bnw { if [[ $1 -ge 20 ]];then bnw $(($1-5)) "$2$3${w[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum sub-optimal delay err array
 function bnc { if [[ $1 -ge 20 ]];then bnc $(($1-5)) "$2$3${c[$1]}" "$3";else echo "$2";fi; }                                                     # recursively sum                   cnt array
 function bro { echo "RSTR $ok $(printf '%3i' $1) $(dnn $(dts) $(bv) $(bq))" >> $p2        ; }                                                     # beacon log restart info
+function brl {                                                                                                                                    # recalculate beacon/bmedias logs
+  [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p3}new ]] && rm ${p3}new
+  unset v;while read -a v;do ok=${v[1]};dt=${v[3]}\ ${v[4]};nn=$(nu9 ${v[5]});nr=${v[6]}                                                          # uncalculated vars
+    if [[ ${v[0]} = BEAC ]];then
+      b0=${v[13]};b5=${v[26]};bl1 ${v[19]} ${v[20]} ${v[22]} ${v[23]} ${v[11]} ${v[15]} ${v[16]} ${v[17]} ${v[18]} ${v[1]};blo                    #  BEAC lines calculated output
+    else
+      m=" $ok $(printf '%3i' ${v[2]}) $(dnn $dt $nn $nr)"                                                                                         # !BEAC lines
+    fi                                                                                                    ;echo "${v[0]}$m" >> ${p2}new           # beacon output
+  done <<< $(cat $p2)
+  [[ ! -f $p3 ]] && return;bm0;local d='0000-00-00';local e='23:58';local l=0;local n=0;local h=0;local g=0;while read -a o;do
+    d=${o[3]};h=$g;g=$(grep -n "$d $e" ${p2}new|cut -d: -f1);dt=${o[3]}\ ${o[4]};nn=$(nu9 ${o[5]});nr=${o[6]}                                     # beacon log position & uncalculated vars
+    b1=$(head -n$g ${p2}new|grep "BEAC.*$e");b2=$(bo3 $d);((l+=b2));((n+=1));b3=$(nu3 $l/$n 5 1)                                                  # cur/avg homologous position
+    b6=$(head -n$g ${p2}new|tail -n$((g-h))|grep BEAC);[[ $b6 ]] && bm1 20;bm2;b4=${o[18]};b8=${o[19]};bmo;echo "${o[0]}$m" >> ${p3}new           # sum err arrays & bmedias output
+  done <<< $(cat $p3)
+}
 function brs {                                                                                                                                    # beacon/validator restart
   [[ -f $p9 ]] && return;touch $p9;local n=0;while [[ -f $p9 && $n -lt 300 ]];do                                                                  # procura posicao ideal restart
     local l=$(fs4 "$bpid].* INFO " 7|sed 's%.* INFO \([^ ]*\).*%\1%'|sort -u)                                                                     # last 7 unique INFO beacon words
@@ -154,21 +168,6 @@ function brs {                                                                  
       if [[ $2 = RB ]];then bro $n;sex reboot;else sex "$sctl start $ethb";[[ $2 = VC ]] && sex "$sctl start $ethv";sleep 20s;bro $n;fi           # beacon log & reboot/start beacon & validator
     fi;sleep 3s;((n+=1))                                                                                                                          # procura ate 200 vezes, every 3s
   done;rm -f $p9
-}
-function brl {                                                                                                                                    # recalculate beacon/bmedias logs
-  [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p3}new ]] && rm ${p3}new
-  unset v;while read -a v;do ok=${v[1]};dt=${v[3]}\ ${v[4]};nn=$(bx ${v[5]});nr=${v[6]}                                                           # uncalculated vars
-    if [[ ${v[0]} = BEAC ]];then
-      b0=${v[13]};b5=${v[26]};bn ${v[19]} ${v[20]} ${v[22]} ${v[23]} ${v[11]} ${v[15]} ${v[16]} ${v[17]} ${v[18]} ${v[1]};blo                     #  BEAC lines calculated output
-    else
-      m=" $ok $(printf '%3i' ${v[2]}) $(dnn $dt $nn $nr)"                                                                                         # !BEAC lines
-    fi                                                                                                    ;echo "${v[0]}$m" >> ${p2}new           # beacon output
-  done <<< $(cat $p2)
-  [[ ! -f $p3 ]] && return;bm0;local d='0000-00-00';local e='23:58';local l=0;local n=0;local h=0;local g=0;while read -a o;do
-    d=${o[3]};h=$g;g=$(grep -n "$d $e" ${p2}new|cut -d: -f1);dt=${o[3]}\ ${o[4]};nn=$(bx ${o[5]});nr=${o[6]}                                      # beacon log position & uncalculated vars
-    b1=$(head -n$g ${p2}new|grep "BEAC.*$e");b2=$(bt $d);((l+=b2));((n+=1));b3=$(nu3 $l/$n 5 1)                                                   # cur/avg homologous position
-    b6=$(head -n$g ${p2}new|tail -n$((g-h))|grep BEAC);[[ $b6 ]] && bm1 20;bm2;b4=${o[18]};b8=${o[19]};bmo;echo "${o[0]}$m" >> ${p3}new           # sum err arrays & bmedias output
-  done <<< $(cat $p3)
 }
 function bsl {                                                                                                                                    # shrink beacon log using barqivo
   [[ -f ${p2}new ]] && rm ${p2}new;[[ -f ${p7}new ]] && rm ${p7}new
@@ -310,7 +309,7 @@ function ssp {
 [[ $1 = bnf ]] && { bm;echo -e "BEAC$s" >> $p7; }
 [[ $1 = gh  ]] && { gh $2; }
 [[ $1 = bh  ]] && { bh $2; }
-[[ $1 = bo  ]] && { bo1 $2 $3;bo2 $2; }
+[[ $1 = bo  ]] && { bo0 $2 $3;bo1 $2; }
 [[ $1 = brl ]] && { [[ -f $p2           ]] && brl; }
 [[ $1 = bsl ]] && { [[ -f $p2 && -f $p7 ]] && bsl; }
 [[ $1 = bnl ]] && { bnl; }
