cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -13,44 +13,43 @@ function nrs { echo -e "${i}RESET NETPLAN & DNS${f}";echo $H|sudo -S netplan app
 function sst { echo "$1 $(printf '%6s' $(echo "$2"|grep Memory:|sed 's%.*Memory: \(.*\)%\1%')) $dt status: $(echo "$2"|grep Active:|sed 's%.*Active: \(.*\)%\1%')"; }
 function nsh {
   echo -e "ROUTES\t\t" $(ip route show|grep 'default via'|grep -v 'linkdown'|cut -d' ' -f3)
-  m=$(ip a|grep 'state UP'|cut -d: -f2)
   echo -e "DNS\t\t" $(resolvectl|grep 'Current DNS'|cut -d' ' -f6)
-  for n in $m;do echo -e "$n\t\t" $(resolvectl dns|grep $n|cut -d' ' -f4-6);done
+  for v in $(ip a|grep 'state UP'|cut -d: -f2);do echo -e "$v\t\t" $(resolvectl dns|grep $v|cut -d' ' -f4-6);done
 }
 function csh {
-  if [[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]];then c1='OK';else c1='NO';fi
+  local e='NO'
+  [[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK'
   m='CLCK'
-  m="$m $c1 $(printf '%3i' $(echo $H|sudo -S grep -i 'check system clock' $p4 2>/dev/null|wc -l))"
+  m="$m $e $(printf '%3i' $(echo $H|sudo -S grep -i 'check system clock' $p4 2>/dev/null|wc -l))"
   m="$m $(date --rfc-3339=seconds)"
   m="$m status: $(systemctl status systemd-timesyncd|grep Active:|sed 's%.*Active: \(.*\)%\1%')"
   echo -e "$m"
 }
 function esh {
-  e1=$(echo $H|sudo -S grep -v 'geth\[\|lighthouse' $p4 2>/dev/null|grep -i 'error' |wc -l)
-  e2=$(echo $H|sudo -S grep -v 'geth\[\|lighthouse' $p4 2>/dev/null|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'|cut -c1-53)
-  e3=$(echo $H|sudo -S grep -i 'geth\[\|lighthouse' $p4 2>/dev/null|grep -v ' INFO '|wc -l)
-  e4=$(echo $H|sudo -S grep -i 'geth\[\|lighthouse' $p4 2>/dev/null|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
+  local l=$(echo $H|sudo -S grep -v 'geth\[\|lighthouse' $p4 2>/dev/null|grep -i 'error' |wc -l)
+  local e=$(echo $H|sudo -S grep -v 'geth\[\|lighthouse' $p4 2>/dev/null|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'|cut -c1-53)
+  local n=$(echo $H|sudo -S grep -i 'geth\[\|lighthouse' $p4 2>/dev/null|grep -v ' INFO '|wc -l)
+  local d=$(echo $H|sudo -S grep -i 'geth\[\|lighthouse' $p4 2>/dev/null|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
   m="ERRO"
-  m="$m $(printf '%2i' $e1)"
-  m="$m $(printf '%3i' $e3)"
+  m="$m $(printf '%2i' $l)"
+  m="$m $(printf '%3i' $n)"
   m="$m $(date --rfc-3339=seconds)"
-  [[ $e1 -gt 0 ]] && m="$m sys: $e2"
-  [[ $e3 -gt 0 ]] && m="$m eth2: $e4"
+  [[ $l -gt 0 ]] && m="$m sys: $e"
+  [[ $n -gt 0 ]] && m="$m eth2: $d"
   echo -e "$m"
 }
 function psh {
-  h5=$(echo $H|sudo -S grep 'e above threshold' $p4 2>/dev/null|head -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%');if [[ $h5 ]];then h5="throttled: $h5";else h5='';fi
-  h6=$(echo $H|sudo -S grep 'ture/speed normal' $p4 2>/dev/null|tail -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%');if [[ $h6 ]];then h6="ok: $h6"       ;else h6='';fi
-  h7=0
-  h8=0
+  local l=0;local n=0
+  local b=$(echo $H|sudo -S grep 'e above threshold' $p4 2>/dev/null|head -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%');if [[ $b ]];then b="throttled: $b";else b='';fi
+  local g=$(echo $H|sudo -S grep 'ture/speed normal' $p4 2>/dev/null|tail -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%');if [[ $g ]];then g="ok: $g"       ;else g='';fi
   if [[ $(which sensors) ]]; then
     for v in $(sensors|grep 'Package\|Core'|sed 's%.*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\1%')
-    do h7=$((h7+1));h8=$(echo "scale=1;$h8$v"|bc)
+    do n=$((n+1));l=$(echo "scale=1;$l$v"|bc)
     done
   else
-    h7=1
+    n=1
   fi
-  echo -e "TEMP $(printf '%5.1f' $(echo "scale=1;$h8/$h7"|bc))C $(date --rfc-3339=seconds) $h5 $h6"
+  echo -e "TEMP $(printf '%5.1f' $(echo "scale=1;$l/$n"|bc))C $(date --rfc-3339=seconds) $b $g"
 }
 # Plex Media Server
 function rxw { cex "ufw$2 allow from 192.168.8.0/24 $1"; }
@@ -130,18 +129,18 @@ function nd { [[ $(systemctl status $ethn 2>/dev/null|grep -i loaded) ]] && { ce
 function fd { [[ $(systemctl status $ethf 2>/dev/null|grep -i loaded) ]] && { cex "systemctl disable $ethf";fcl;cex 'ufw reload'; } }
 # geth control functions
 function gv {
-  local g="http://$zip1:8545"
-  [[ $cunm = $vnm1 ]] && g="http://$vip1:8545"
-  g1=$(geth attach $g --exec eth.syncing   2>/dev/null)
-  g2=$(geth attach $g --exec net.peerCount 2>/dev/null)
+  local e="http://$zip1:8545"
+  [[ $cunm = $vnm1 ]] && e="http://$vip1:8545"
+  g1=$(geth attach $e --exec eth.syncing   2>/dev/null)
+  g2=$(geth attach $e --exec net.peerCount 2>/dev/null)
   # IMPORTANT DO NOT USE [[
   [ ${g2:-0} -eq $g2 ] 2>/dev/null || g2=0
 }
 function gb {
   g0=$(echo $H|sudo -S grep -i 'imported new' $p4 2>/dev/null|wc -l)
   g7='OK'
-  local t=$(grep -i blocks: $p5 2>/dev/null|tail -n1|sed 's%.*blocks: *\([0-9]*\).*%\1%')
-  if [[ $((g0*${t:-0})) -eq 0 ]];then g7='NOT';else if [[ $g0 -eq ${t:-0} ]];then g7='BK';fi;fi
+  local g=$(grep -i blocks: $p5 2>/dev/null|tail -n1|sed 's%.*blocks: *\([0-9]*\).*%\1%')
+  if [[ $((g0*${g:-0})) -eq 0 ]];then g7='NOT';else if [[ $g0 -eq ${g:-0} ]];then g7='BK';fi;fi
 }
 function gs {
   dt=$(date --rfc-3339=seconds)
@@ -150,11 +149,11 @@ function gs {
     if [[ $(echo $g1|grep -i false) ]]; then
       m="SYNCED $dt nodes: $(printf '%2i' $g2)"
     else
-      local h=$(echo $g1|sed -Ee 's%.*highestBlock: *([0-9]+).*%\1%i')
-      local c=$(echo $g1|sed -Ee 's%.*currentBlock: *([0-9]+).*%\1%i')
-      local k=$(echo $g1|sed -Ee 's%.*knownStates: *([0-9]+).*%\1%i')
-      local p=$(echo $g1|sed -Ee 's%.*pulledStates: *([0-9]+).*%\1%i')
-      m="SYNCING $dt nodes: $(printf '%2i' $g2) blocks: $h ($((h-c))) states: $k ($((k-p)))"
+      local g=$(echo $g1|sed -Ee 's%.*highestBlock: *([0-9]+).*%\1%i')
+      local n=$(echo $g1|sed -Ee 's%.*currentBlock: *([0-9]+).*%\1%i')
+      local l=$(echo $g1|sed -Ee 's%.*knownStates: *([0-9]+).*%\1%i')
+      local b=$(echo $g1|sed -Ee 's%.*pulledStates: *([0-9]+).*%\1%i')
+      m="SYNCING $dt nodes: $(printf '%2i' $g2) blocks: $g ($((g-n))) states: $l ($((l-b)))"
     fi
   else
     m="NOT HERE $dt"
@@ -170,9 +169,9 @@ function gk {
 function grs {
   if [[ $1 -ne 0 ]]; then
     cp /etc/systemd/system/$ethg.service ~/$ethg.save
-    local p=$(grep maxpeers ~/$ethg.save|sed 's%.*maxpeers \([0-9]*\).*%\1%')
-    p=$((p+$1))
-    [[ $p -ge 10 && $p -le 15 ]] && sed "s%--maxpeers [0-9]*%--maxpeers $p%" ~/$ethg.save > /etc/systemd/system/$ethg.service
+    local n=$(grep maxpeers ~/$ethg.save|sed 's%.*maxpeers \([0-9]*\).*%\1%')
+    n=$((n+$1))
+    [[ $n -ge 10 && $n -le 15 ]] && sed "s%--maxpeers [0-9]*%--maxpeers $n%" ~/$ethg.save > /etc/systemd/system/$ethg.service
   fi
   resolvectl query smtp.gmail.com 2>/dev/null 1>&2
   echo $H|sudo -S systemctl stop  $ethg   2>/dev/null
@@ -198,7 +197,7 @@ function bb {
   c=$(echo $(echo $H|sudo -S grep -i 'attestation(s).*target' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
   h=$(echo $(echo $H|sudo -S grep -i 'attestation(s).*head'   $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
   k=$(echo $(echo $H|sudo -S grep -i 'attestation(s) had'     $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  local n=$(bu)
+  n=$(bu)
   b7='OK'
   if [[ -f $p2 && $n -ge $l1rs ]]; then
     if [[ $n -ge $l2rs ]]; then
@@ -256,28 +255,23 @@ function bhr {
     echo -e "${v[0]} $m" >> ${p2}new
   done <<< $(cat $p2)
 
-  h2='23:58';h9=0;bm0
-  local l=0;local n=0
+  bm0
+  local e='23:58';local d='0000-00-00'
+  local l=0;local n=0;local b=0;local g=0
   while read -a o;do
-    h1="${o[3]}"
-    h0=$h9
-    h9=$(grep -n "$h1 $h2" ${p2}new|cut -d: -f1)
-    h3=$(head -n  $h9      ${p2}new|grep "BEAC.*$h2"|sort -k10.1n|grep -n $h1|cut -d: -f1);l=$((h3+l));n=$((1+n))
-    b1=$h3
-    b3=$(printf '%.0f' $(echo "scale=5;$l/$n"|bc))
-    b2=${o[6]}
+    d=${o[3]};b=$g;g=$(grep -n "$d $e" ${p2}new|cut -d: -f1)
+    b6=$(head -n$g ${p2}new|grep "BEAC.*$e"|sort -k10.1n|grep -n $d|cut -d: -f1);l=$((b6+l));n=$((1+n))
+    b2=${o[6]};b1=$b6;b3=$(printf '%.0f' $(echo "scale=5;$l/$n"|bc));dt="${o[3]} ${o[4]}"
     if [[ ${#o[@]} -gt 16 ]];then b4=" ${o[16]}";else b4='';fi
-    dt="${o[3]} ${o[4]}"
-    while read -a v;do bm1;done <<< $(head -n$h9 ${p2}new|tail -n$((h9-h0))|grep BEAC)
-    bm2
-    bmo
+    while read -a v;do bm1;done <<< $(head -n$g ${p2}new|tail -n$((g-b))|grep BEAC)
+    bm2;bmo
     echo -e "${o[0]} $m" >> ${p3}new
   done <<< $(cat $p3)
 }
 function bmo {
   #    0  1   2          3              4      5  6    7    8    9   10   11   12   13   14    15
   # BEAC  2   1 2021-11-14 16:16:34+00:00 nodes: 20 avg: 0.00 0.00 0.00 0.00 0.00 0.00 1.75  1.75
-  m="$(printf '%2i' $b3) $(printf '%3i' $h3) $dt nodes: $(printf '%2i' $b2)"
+  m="$(printf '%2i' $b3) $(printf '%3i' $b6) $dt nodes: $(printf '%2i' $b2)"
   m="$m avg: $(printf '%4.2f' $a50) $(printf '%4.2f' $a45) $(printf '%4.2f' $a40) $(printf '%4.2f' $a35) $(printf '%4.2f' $a30) $(printf '%4.2f' $a25) $(printf '%4.2f' $a20)"
   m="$m $(printf '%5.2f' $a00)$b4"
   #    0      1          2              3    4 5 6 7 8 9 0   1    2 3 4 5 6 7 8   9    0 1 2 3 4 5 6    7    8 9 0 1 2 3 4     5    6 7 8 9 0 1 2    3
@@ -336,10 +330,11 @@ function bm2 {
 }
 function bm {
   bm0
-  r0=0;b1=0
+  local l=0;local n=0;local b=0
+  b1=0
   if [[ -f $p7 ]]; then
     read -a o <<< $(tail -n1 $p7)
-    r0=${o[1]}
+    b=${o[1]}
     c50=${o[ 5]};c45=${o[ 6]};c40=${o[ 7]};c35=${o[ 8]};c30=${o[ 9]};c25=${o[10]};c20=${o[11]}
     k50=${o[13]};k45=${o[14]};k40=${o[15]};k35=${o[16]};k30=${o[17]};k25=${o[18]};k20=${o[19]}
     z50=${o[21]};z45=${o[22]};z40=${o[23]};z35=${o[24]};z30=${o[25]};z25=${o[26]};z20=${o[27]}
@@ -348,13 +343,12 @@ function bm {
   fi
   if [[ -f $p2 ]]; then
     b1=$(cat $p2|wc -l)
-    while read -a v;do bm1;done <<< $(tail -n$((b1-r0)) $p2|grep BEAC)
+    while read -a v;do bm1;done <<< $(tail -n$((b1-b)) $p2|grep BEAC)
   fi
   bm2
-  [[ ${h3:-0} -eq 0 ]] && bo
-  local l=0;local n=0
+  [[ ${b6:-0} -eq 0 ]] && bo
   [[ -f $p3 ]] && while read -a v;do l=$((${v[2]}+l));n=$((1+n));done <<< $(cat $p3)
-  b3=$(printf '%.0f' $(echo "scale=5;($l+$h3)/(1+$n)"|bc))
+  b3=$(printf '%.0f' $(echo "scale=5;($l+$b6)/(1+$n)"|bc))
   b2=$(systemctl status eth-beacon|grep target-peers|sed 's%.*target-peers \([0-9]*\).*%\1%')
   # IMPORTANT DO NOT USE [[
   [ ${b2:-0} -eq $b2 ] 2>/dev/null || b2=0
@@ -387,39 +381,37 @@ function bm {
   [[ $(printf '%.0f' $(echo "$a45*100"|bc)) -lt $(printf '%.0f' $(echo "$l*100"|bc)) ]] && { l=$a45;b5=$((45-b2)); }
   [[ $(printf '%.0f' $(echo "$a50*100"|bc)) -lt $(printf '%.0f' $(echo "$l*100"|bc)) ]] && { l=$a50;b5=$((50-b2)); }
   [[ $(tail -n $hors $p2|cut -d' ' -f1|sort -u) = BEAC ]] && b5=0
-  if [[ ($h3 -gt $b3 && $(printf '%.0f' $(echo "$n*100"|bc)) -ge $(printf '%.0f' $(echo "$a00*100"|bc))) && $b5 -ne 0 ]];then b4=" PEERS_$b5";else b4='';b5=0;fi
+  if [[ ($b6 -gt $b3 && $(printf '%.0f' $(echo "$n*100"|bc)) -ge $(printf '%.0f' $(echo "$a00*100"|bc))) && $b5 -ne 0 ]];then b4=" PEERS_$b5";else b4='';b5=0;fi
   bmo
 }
 function boo {
   if [[ -f $p2 ]]; then
-    h0=${h3:-0};h9=${h3:-0}
-    if [[ $(echo $1|egrep '^[0-9]+$') ]];then h9=$1;else if [[ $h9 -lt $l2rs && $(echo "$b0"|wc -l) -ge $l2rs ]];then h0=$l2rs;h9=$l2rs;fi;fi
-    if [[ $(echo $1|egrep '^[0-9]+$') ]];then h0=$1;else if [[ $h0 -gt $hors ]];then h0=$hors;fi;fi
-    echo "$b0"|sort -k10.1n|head -n$h9|tail -n$h0
+    local b=${b6:-0};local g=${b6:-0}
+    if [[ $(echo $1|egrep '^[0-9]+$') ]];then g=$1;else if [[ $g -lt $l2rs && $(echo "$b0"|wc -l) -ge $l2rs ]];then b=$l2rs;g=$l2rs;fi;fi
+    if [[ $(echo $1|egrep '^[0-9]+$') ]];then b=$1;else if [[ $b -gt $hors ]];then b=$hors;fi;fi
+    echo "$b0"|sort -k10.1n|head -n$g|tail -n$b
   fi
 }
 function bo {
-  h2='00:00';h3=0
+  b6=0
   if [[ -f $p2 ]]; then
-    local o=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\):.*%\1 \2%')
-    h1=$(echo $o|cut -d' ' -f1)
-    if [[ $(echo $1|egrep '^[0-9]+:[0-9]+$') ]];then h2=$1;else if [[ $(echo $2|egrep '^[0-9]+:[0-9]+$') ]];then h2=$2;else h2=$(echo $o|cut -d' ' -f2);fi;fi
-    b0=$(grep "BEAC.*$h2" $p2)
-    if [[ $(echo $1|egrep '^[0-9]+$')        ]];then h3=$1;else if [[ $(echo $2|egrep '^[0-9]+$')        ]];then h3=$2;else h3=$(echo "$b0"|sort -k10.1n|grep -n $h1|cut -d: -f1);fi;fi
+    local e='00:00'
+    local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\):.*%\1 \2%')
+    local d=$(echo $l|cut -d' ' -f1)
+    if [[ $(echo $1|egrep '^[0-9]+:[0-9]+$') ]];then e=$1 ;else if [[ $(echo $2|egrep '^[0-9]+:[0-9]+$') ]];then e=$2 ;else e=$(echo $l|cut -d' ' -f2);fi;fi
+    b0=$(grep "BEAC.*$e" $p2)
+    if [[ $(echo $1|egrep '^[0-9]+$')        ]];then b6=$1;else if [[ $(echo $2|egrep '^[0-9]+$')        ]];then b6=$2;else b6=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1);fi;fi
     local n=0
-    while [[ ${h3:-0} -eq 0 && $n -lt 50 ]];do
-      n=$((n+1))
-      h1=$(date -d "$n days ago $h2" '+%Y-%m-%d')
-      h3=$(echo "$b0"|sort -k10.1n|grep -n $h1|cut -d: -f1)
+    while [[ ${b6:-0} -eq 0 && $n -lt 50 ]];do
+      n=$((n+1));d=$(date -d "$n days ago $e" '+%Y-%m-%d')
+      b6=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1)
     done
   fi 
 }
 function bh {
-  [[ $1 ]] || echo -e "BH $(printf '%8i' $((${1:-$hors}-$l2rs)))"
-  tail -n${1:-$hors} $p2|head -n$((${1:-$hors}-$l2rs))
-  [[ $1 ]] || echo -e "BH $(printf '%8i' $l2rs)"
-  tail -n$l2rs       $p2|head -n$l2rs
-  [[ $1 ]] || { bo;echo -e "BO $(printf '%8i' $h3)/$(echo "$b0"|wc -l)";boo; }
+  [[ $1 ]] || echo -e "BH $(printf '%8i' ${1:-$hors})"
+  tail -n${1:-$hors} $p2
+  [[ $1 ]] || { bo;echo -e "BO $(printf '%8i' $b6)/$(echo "$b0"|wc -l)";boo; }
   [[ $1 ]] || { bk;echo -e "BL\nBEAC $m"; }
   [[ $1 ]] || { bm;echo -e "BM $(printf '%8i' $b1)\nBEAC $m"; }
   [[ $1 ]] || { sst BEAC "$(systemctl status $ethb)";sst VALI "$(systemctl status $ethv)"; }
@@ -432,13 +424,13 @@ function brs {
         touch /home/eth/beacon.restart.interval
         local n=0
         while [[ $n -lt 400 && -f /home/eth/beacon.restart.interval ]]; do
-          local o=$(echo $H|sudo -S grep "lighthouse.$bpid.* INFO " $p4 2>/dev/null|tail -n$pors|sed 's%.* INFO \([^ ]*\) .*%\1%'|sort -u)
-          local k=$(echo "$o"|head -n1)
-          if [[ $(echo "$o"|wc -l) -eq 2 && $(echo "$o"|tail -n1) = Synced && ( $k = New || $k = Processed ) ]]; then
+          local l=$(echo $H|sudo -S grep "lighthouse.$bpid.* INFO " $p4 2>/dev/null|tail -n$pors|sed 's%.* INFO \([^ ]*\) .*%\1%'|sort -u)
+          local b=$(echo "$l"|head -n1)
+          if [[ $(echo "$l"|wc -l) -eq 2 && $(echo "$l"|tail -n1) = Synced && ( $b = New || $b = Processed ) ]]; then
             if [[ $1 -ne 0 ]]; then
               cp /etc/systemd/system/$ethb.service ~/$ethb.save
-              local p=$(($(grep target-peers ~/$ethb.save|sed 's%.*target-peers \([0-9]*\).*%\1%')+$1))
-              [[ $p -ge 20 && $p -le 50 ]] && sed "s%--target-peers [0-9]*%--target-peers $p%" ~/$ethb.save > /etc/systemd/system/$ethb.service
+              local g=$(($(grep target-peers ~/$ethb.save|sed 's%.*target-peers \([0-9]*\).*%\1%')+$1))
+              [[ $g -ge 20 && $g -le 50 ]] && sed "s%--target-peers [0-9]*%--target-peers $p%" ~/$ethb.save > /etc/systemd/system/$ethb.service
             fi
             bk
             if [[ $2 || $b7 != 'OK' ]]; then
