cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -3,6 +3,7 @@
 source /home/eth/eth2/t1
 
 # utilities for commands/journal
+function num { if [ ${1:-0} -eq $1 ] 2>/dev/null;then echo $1;else echo 0;fi; }
 function eip { curl -s4 "http://${1}:${2}@dyn.dns.he.net/nic/update?hostname=${1}" 2>/dev/null 1>&2; }
 function cex { echo -e "${i}$1${f}";echo $H|sudo -S $1 2>/dev/null; }
 function jsh { cex "journalctl --no-hostname --no-full -f $1"; }
@@ -129,17 +130,16 @@ function nd { [[ $(systemctl status $ethn 2>/dev/null|grep -i loaded) ]] && { ce
 function fd { [[ $(systemctl status $ethf 2>/dev/null|grep -i loaded) ]] && { cex "systemctl disable $ethf";fcl;cex 'ufw reload'; } }
 # geth control functions
 function gv {
-  local e="http://$zip1:8545";[[ $cunm = $vnm1 ]] && e="http://$vip1:8545"
+  local d=$zip1;[[ $cunm = $vnm1 ]] && d=$vip1
+  local e="http://$d:8545"
   dt=$(date --rfc-3339=seconds)
   g1=$(geth attach $e --exec eth.syncing   2>/dev/null)
-  nn=$(geth attach $e --exec net.peerCount 2>/dev/null)
-  # DO NOT USE [[
-  [ ${nn:-0} -eq $nn ] 2>/dev/null || nn=0
+  nn=$(num $(geth attach $e --exec net.peerCount 2>/dev/null))
 }
 function gb {
   ok='OK'
   g0=$(echo $H|sudo -S grep -i 'imported new' $p4 2>/dev/null|wc -l)
-  local g=$(grep -i blocks: $p5 2>/dev/null|tail -n1|sed 's%.*blocks: *\([0-9]*\).*%\1%')
+  local g=$(num $(grep -i blocks: $p5 2>/dev/null|tail -n1|sed 's%.*blocks: *\([0-9]*\).*%\1%'))
   if [[ $((g0*g)) -eq 0 ]];then ok='NOT';else if [[ $g0 -eq $g ]];then ok='BK';fi;fi
 }
 function gk {
@@ -165,50 +165,48 @@ function gs {
   fi
 }
 function grs {
+  m="RESTAR $(date --rfc-3339=seconds)"
   if [[ $1 -ne 0 ]]; then
     cp /etc/systemd/system/$ethg.service ~/$ethg.save
-    local n=$(grep maxpeers ~/$ethg.save|sed 's%.*maxpeers \([0-9]*\).*%\1%')
-    n=$((n+$1))
-    [[ $n -ge 10 && $n -le 15 ]] && sed "s%--maxpeers [0-9]*%--maxpeers $n%" ~/$ethg.save > /etc/systemd/system/$ethg.service
+    nn=$(num $(($(grep maxpeers ~/$ethg.save|sed 's%.*maxpeers \([0-9]*\).*%\1%')+$1)))
+    if [[ $nn -ge 10 && $nn -le 15 ]]; then
+      sed "s%--maxpeers [0-9]*%--maxpeers $nn%" ~/$ethg.save > /etc/systemd/system/$ethg.service
+      m="$m nodes: $(printf '%2i' $nn)"
+    fi
   fi
   resolvectl query smtp.gmail.com 2>/dev/null 1>&2
   echo $H|sudo -S systemctl stop  $ethg   2>/dev/null
-  echo $H|sudo -S systemctl daemon-reload 2>/dev/null;sleep 30s
+  echo $H|sudo -S systemctl daemon-reload 2>/dev/null
   echo $H|sudo -S systemctl start $ethg   2>/dev/null
-  echo -e "GETH RESTAR $(date --rfc-3339=seconds)" >> $p5
+  echo -e "GETH $m" >> $p5
 }
 # beacon control functions
 function bt { if [[ $3 -gt $1 ]];then echo $(($2/$3));else echo 0;fi; }
-function bz { echo $((10*(13*b15+3*b16+b17+b18))); }
-function bw { echo $((10*b19)); }
-function br { echo $((90*b22)); }
+function bz { echo $((10*(13*z6+3*z7+z8+z9))); }
+function bw { echo $((10*z1)); }
+function br { echo $((90*z3)); }
 function bs { echo $(tail -n$1 $p2 2>/dev/null|cut -d' ' -f1|sort -u|wc -l); }
-function bu { echo $(($(bt 200 $(bz) $b11)+$(bt 100 $(bw) $b20)+$(bt 100 $(br) $b23))); }
+function bu { echo $(($(bt 200 $(bz) $z5)+$(bt 100 $(bw) $z2)+$(bt 100 $(br) $z4))); }
 function bx { if [[ $1 -ge ${2:-25} && ${2:-25} -le 50 ]];then echo $(bx $1 $((${2:-25}+5)));else echo $((${2:-25}-5));fi; }
 function bb {
   local e=$(echo $H|sudo -S grep "lighthouse.$bpid" $p4 2>/dev/null|tail -n3600)
-  b19=$(echo "$e"|grep    'processed block'|wc -l)
-  b20=$(echo "$e"|grep    'block received' |wc -l)
-  b22=$(echo "$e"|grep -v ' INFO '|wc -l)
-  b23=$(echo "$e"|grep    ' INFO '|wc -l)
-  b11=$(echo $(echo $H|sudo -S grep 'attestation(s) success' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  b15=$(echo $(echo $H|sudo -S grep 'attestation(s) missing' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  b16=$(echo $(echo $H|sudo -S grep 'attestation(s).*target' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  b17=$(echo $(echo $H|sudo -S grep 'attestation(s).*head'   $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  b18=$(echo $(echo $H|sudo -S grep 'attestation(s) had'     $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
-  local n=$(bu)
-  ok='OK'
-  [[ $n -ge $l1rs ]] && if [[ $n -ge $l2rs ]];then [[ $(bs $l2rs) -eq 1 ]] && ok='BK';else [[ $(bs $hors) -eq 1 ]] && ok='BK';fi
+  z1=$(echo "$e"|grep    'processed block'|wc -l)
+  z2=$(echo "$e"|grep    'block received' |wc -l)
+  z3=$(echo "$e"|grep -v ' INFO '         |wc -l)
+  z4=$(echo "$e"|grep    ' INFO '         |wc -l)
+  z5=$(echo $(echo $H|sudo -S grep 'attestation(s) success' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
+  z6=$(echo $(echo $H|sudo -S grep 'attestation(s) missing' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
+  z7=$(echo $(echo $H|sudo -S grep 'attestation(s).*target' $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
+  z8=$(echo $(echo $H|sudo -S grep 'attestation(s).*head'   $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
+  z9=$(echo $(echo $H|sudo -S grep 'attestation(s) had'     $p4 2>/dev/null|sed 's%.*validators: *\[\(.*\)\].*%\1%;s%[,"]%%g')|wc -w)
+  ok='OK';local g=$(bu)
+  [[ $g -ge $l1rs ]] && if [[ $g -ge $l2rs ]];then [[ $(bs $l2rs) -eq 1 ]] && ok='BK';else [[ $(bs $hors) -eq 1 ]] && ok='BK';fi
 }
 function bk {
-  b26=0
-  b13=$(echo $H|sudo -S grep 'ublished block' $p4 2>/dev/null|wc -l)
-  local l=0;local n=0
-  for v in $(echo $H|sudo -S grep 'src: gossip,' $p4 2>/dev/null|sed 's%.*delay_ms: *\([0-9]*\).*%\1%');do n=$((n+1));l=$((l+v));done;[[ $n -gt 0 ]] && b26=$((l/n))
+  b6=$(echo $H|sudo -S grep 'ublished block' $p4 2>/dev/null|wc -l)
+  b7=0;local l=0;local n=0;for v in $(echo $H|sudo -S grep 'src: gossip,' $p4 2>/dev/null|sed 's%.*delay_ms: *\([0-9]*\).*%\1%');do n=$((n+1));l=$((l+v));done;[[ $n -gt 0 ]] && b7=$((l/n))
   dt=$(date --rfc-3339=seconds)
-  nn=$(echo $H|sudo -S grep 'lighthouse.*peers:' $p4 2>/dev/null|tail -n1|sed 's%.*peers: *\([0-9]*\).*%\1%')
-  # DO NOT USE [[
-  [ ${nn:-0} -eq $nn ] 2>/dev/null || nn=0
+  nn=$(num $(echo $H|sudo -S grep 'lighthouse.*peers:' $p4 2>/dev/null|tail -n1|sed 's%.*peers: *\([0-9]*\).*%\1%'))
   bb;bko
 }
 function bko {
@@ -216,18 +214,18 @@ function bko {
   # BEAC OK   0 2021-11-22 17:15:58+00:00 nodes: 32 reward_penalty: 224 3.54 attestation_block: 2950 2280 0 erros: 2 14 131 29      0 537   0   14 3586 1260     delay: 1000
   m="$ok $(printf '%3i' $(bu)) $dt"
   m="$m nodes: $(printf '%2i' $nn) reward_penalty:"
-  m="$m $(printf '%3i'   $(echo "scale=0;($b11*$ratt+$b13*$rblk)*$rate/$decp"|bc))"
-  m="$m $(printf '%3.2f' $(echo "scale=2;($b15*$pmis+$b16*$pmat+$b17*$pmah+$b18*$pdly)*$rate/$decp"|bc))"
-  m="$m attestation_block: $(printf '%4i' $b11) $(printf '%4i' $(bz)) $(printf '%1i' $b13)"
-  m="$m erros: $(printf '%1i' $b15) $(printf '%2i' $b16) $(printf '%3i' $b17) $(printf '%2i' $b18)"
-  m="$m $(printf '%6i' $b19) $(printf '%3i' $b20) $(printf '%3i' $(bw))"
-  m="$m $(printf '%4i' $b22) $(printf '%4i' $b23) $(printf '%4i' $(br))    "
-  m="$m delay: $(printf '%4i' $b26)"
+  m="$m $(printf '%3i'   $(echo "scale=0;($z5*$ratt+$b6*$rblk)*$rate/$decp"|bc))"
+  m="$m $(printf '%3.2f' $(echo "scale=2;($z6*$pmis+$z7*$pmat+$z8*$pmah+$z9*$pdly)*$rate/$decp"|bc))"
+  m="$m attestation_block: $(printf '%4i' $z5) $(printf '%4i' $(bz)) $(printf '%1i' $b6)"
+  m="$m erros: $(printf '%1i' $z6) $(printf '%2i' $z7) $(printf '%3i' $z8) $(printf '%2i' $z9)"
+  m="$m $(printf '%6i' $z1) $(printf '%3i' $z2) $(printf '%3i' $(bw))"
+  m="$m $(printf '%4i' $z3) $(printf '%4i' $z4) $(printf '%4i' $(br))    "
+  m="$m delay: $(printf '%4i' $b7)"
 }
 function bmo {
   #    0  1   2          3              4      5  6    7    8    9   10   11   12   13   14    15
   # BEAC  2   1 2021-11-14 16:16:34+00:00 nodes: 20 avg: 0.00 0.00 0.00 0.00 0.00 0.00 1.75  1.75
-  m="$(printf '%2i' $b3) $(printf '%3i' $b6) $dt nodes: $(printf '%2i' $nn)"
+  m="$(printf '%2i' $b3) $(printf '%3i' $b2) $dt nodes: $(printf '%2i' $nn)"
   m="$m avg: $(printf '%4.2f' ${a[50]}) $(printf '%4.2f' ${a[45]}) $(printf '%4.2f' ${a[40]}) $(printf '%4.2f' ${a[35]}) $(printf '%4.2f' ${a[30]}) $(printf '%4.2f' ${a[25]}) $(printf '%4.2f' ${a[20]})"
   m="$m $(printf '%5.2f' ${a[00]})$b4"
   #    0      1          2              3    4 5 6 7 8 9 0   1    2 3 4 5 6 7 8   9    0 1 2 3 4 5 6    7    8 9 0 1 2 3 4     5    6 7 8 9 0 1 2    3
@@ -244,20 +242,20 @@ function bhr {
   [[ -f ${p3}new ]] && rm ${p3}new 
 
   while read -a v;do
-    dt=${v[3]}\ ${v[4]}
     ok=${v[1]}
+    dt=${v[3]}\ ${v[4]}
     nn=${v[6]}
-    b11=${v[11]} # attestation
-    b13=${v[13]} # block
-    b15=${v[15]} # erros missing
-    b16=${v[16]} # erros target
-    b17=${v[17]} # erros head
-    b18=${v[18]} # erros had
-    b19=${v[19]} # processed block
-    b20=${v[20]} # block received
-    b22=${v[22]} # not INFO
-    b23=${v[23]} #     INFO
-    b26=${v[26]} # delay
+    b6=${v[13]} # published block
+    b7=${v[26]} # delay
+    z1=${v[19]} # processed block
+    z2=${v[20]} # block received
+    z3=${v[22]} # not INFO
+    z4=${v[23]} #     INFO
+    z5=${v[11]} # attestation
+    z6=${v[15]} # erros missing
+    z7=${v[16]} # erros target
+    z8=${v[17]} # erros head
+    z9=${v[18]} # erros had
     bko
     echo -e "${v[0]} $m" >> ${p2}new
   done <<< $(cat $p2)
@@ -271,7 +269,7 @@ function bhr {
     g=$(grep -n "$d $e" ${p2}new|cut -d: -f1)
     dt=${o[3]}\ ${o[4]}
     nn=${o[6]}
-    b6=$(head -n$g ${p2}new|grep "BEAC.*$e"|sort -k10.1n|grep -n $d|cut -d: -f1);l=$((b6+l));n=$((1+n))
+    b2=$(head -n$g ${p2}new|grep "BEAC.*$e"|sort -k10.1n|grep -n $d|cut -d: -f1);l=$((b2+l));n=$((1+n))
     b3=$(printf '%.0f' $(echo "scale=5;$l/$n"|bc))
     while read -a v;do bm1;done <<< $(head -n$g ${p2}new|tail -n$((g-b))|grep BEAC)
     if [[ ${#o[@]} -gt 16 ]];then b4=" ${o[16]}";else b4='';fi
@@ -314,9 +312,7 @@ function bm {
   bm0
   local b=0
   b1=0
-  nn=$(systemctl status eth-beacon|grep target-peers|sed 's%.*target-peers \([0-9]*\).*%\1%')
-  # DO NOT USE [[
-  [ ${nn:-0} -eq $nn ] 2>/dev/null || nn=0
+  nn=$(num $(systemctl status eth-beacon|grep target-peers|sed 's%.*target-peers \([0-9]*\).*%\1%'))
   dt=$(date --rfc-3339=seconds)
   if [[ -f $p7 ]]; then
     read -a o <<< $(tail -n1 $p7)
@@ -332,10 +328,10 @@ function bm {
     while read -a v;do bm1;done <<< $(tail -n$((b1-b)) $p2|grep BEAC)
   fi
   bm2
-  [[ ${b6:-0} -eq 0 ]] && bo
+  [[ ${b2:-0} -eq 0 ]] && bo
   local l=0;local n=0
   [[ -f $p3 ]] && while read -a v;do l=$((${v[2]}+l));n=$((1+n));done <<< $(cat $p3)
-  b3=$(printf '%.0f' $(echo "scale=5;($l+$b6)/(1+$n)"|bc))
+  b3=$(printf '%.0f' $(echo "scale=5;($l+$b2)/(1+$n)"|bc))
   b4=''
   b5=0;l=${a[$nn]}
   [[ $(printf '%.0f' $(echo "${a[20]}*100"|bc)) -lt $(printf '%.0f' $(echo "$l*100"|bc)) ]] && { l=${a[20]};b5=$((20-nn)); }
@@ -346,49 +342,46 @@ function bm {
   [[ $(printf '%.0f' $(echo "${a[45]}*100"|bc)) -lt $(printf '%.0f' $(echo "$l*100"|bc)) ]] && { l=${a[45]};b5=$((45-nn)); }
   [[ $(printf '%.0f' $(echo "${a[50]}*100"|bc)) -lt $(printf '%.0f' $(echo "$l*100"|bc)) ]] && { l=${a[50]};b5=$((50-nn)); }
   [[ $(bs $hors) -gt 1 ]] && b5=0
-  [[ ($b6 -gt $b3 && $(printf '%.0f' $(echo "${a[$nn]}*100"|bc)) -ge $(printf '%.0f' $(echo "${a[00]}*100"|bc))) && $b5 -ne 0 ]] && b4=" PEERS$b5"
+  [[ ($b2 -gt $b3 && $(printf '%.0f' $(echo "${a[$nn]}*100"|bc)) -ge $(printf '%.0f' $(echo "${a[00]}*100"|bc))) && $b5 -ne 0 ]] && b4=" PEERS$b5"
   bmo
 }
 function boo {
   if [[ -f $p2 ]]; then
-    local b=${b6:-0};local g=${b6:-0}
+    local b=${b2:-0};local g=${b2:-0}
     if [[ $(echo $1|egrep '^[0-9]+$') ]];then g=$1;else if [[ $g -lt $l2rs && $(echo "$b0"|wc -l) -ge $l2rs ]];then b=$l2rs;g=$l2rs;fi;fi
     if [[ $(echo $1|egrep '^[0-9]+$') ]];then b=$1;else if [[ $b -gt $hors ]];then b=$hors;fi;fi
     echo "$b0"|sort -k10.1n|head -n$g|tail -n$b
   fi
 }
 function bo {
-  b6=0
+  b2=0
   if [[ -f $p2 ]]; then
     local e='00:00'
     local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\):.*%\1 \2%')
     local d=$(echo $l|cut -d' ' -f1)
     if [[ $(echo $1|egrep '^[0-9]+:[0-9]+$') ]];then e=$1 ;else if [[ $(echo $2|egrep '^[0-9]+:[0-9]+$') ]];then e=$2 ;else e=$(echo $l|cut -d' ' -f2);fi;fi
     b0=$(grep "BEAC.*$e" $p2)
-    if [[ $(echo $1|egrep '^[0-9]+$')        ]];then b6=$1;else if [[ $(echo $2|egrep '^[0-9]+$')        ]];then b6=$2;else b6=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1);fi;fi
+    if [[ $(echo $1|egrep '^[0-9]+$')        ]];then b2=$1;else if [[ $(echo $2|egrep '^[0-9]+$')        ]];then b2=$2;else b2=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1);fi;fi
     local n=0
-    while [[ ${b6:-0} -eq 0 && $n -lt 50 ]];do
+    while [[ ${b2:-0} -eq 0 && $n -lt 50 ]];do
       n=$((n+1));d=$(date -d "$n days ago $e" '+%Y-%m-%d')
-      b6=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1)
+      b2=$(echo "$b0"|sort -k10.1n|grep -n $d|cut -d: -f1)
     done
   fi 
 }
 function bh {
   [[ $1 ]] || echo -e "BH $(printf '%8i' ${1:-$hors})"
   tail -n${1:-$hors} $p2
-  [[ $1 ]] || { bo;echo -e "BO $(printf '%8i' $b6)/$(echo "$b0"|wc -l)";boo; }
+  [[ $1 ]] || { bo;echo -e "BO $(printf '%8i' $b2)/$(echo "$b0"|wc -l)";boo; }
   [[ $1 ]] || { bk;echo -e "BL\nBEAC $m"; }
   [[ $1 ]] || { bm;echo -e "BM $(printf '%8i' $b1)\nBEAC $m"; }
   [[ $1 ]] || { sst BEAC "$(systemctl status $ethb)";sst VALI "$(systemctl status $ethv)"; }
+  ok=
+  echo $ok
+  
+  echo $ok
 }
 function brs {
-  #while [[ -f /home/eth/beacon.restart.inicio ]]; do
-  #if [[ $(echo $H|sudo -S grep Synced $p4 2>/dev/null|tail -n32|sed 's%.* epoch: \([0-9]*\).*%\1%'|sort -u|wc -l) -eq 1 ]]; then
-  #touch /home/eth/beacon.restart.interval
-  #rm -f /home/eth/beacon.restart.interval
-  #fi
-  #sleep 1s
-  #done
   if [[ ! -f /home/eth/beacon.restart.inicio ]]; then
     touch /home/eth/beacon.restart.inicio
     local n=0
@@ -396,21 +389,19 @@ function brs {
       local l=$(echo $H|sudo -S grep "lighthouse.$bpid.* INFO " $p4 2>/dev/null|tail -n$pors|sed 's%.* INFO \([^ ]*\) .*%\1%'|sort -u)
       local b=$(echo "$l"|head -n1)
       if [[ $(echo "$l"|wc -l) -eq 2 && $(echo "$l"|tail -n1) = Synced && ( $b = New || $b = Processed ) ]]; then
+        rm -f /home/eth/beacon.restart.inicio;n=400;bk;[[ $2 ]] && { ok=${2:0:2};ok=${ok^^}; }
         if [[ $1 -ne 0 ]]; then
           cp /etc/systemd/system/$ethb.service ~/$ethb.save
-          local g=$(($(grep target-peers ~/$ethb.save|sed 's%.*target-peers \([0-9]*\).*%\1%')+$1))
-          [[ $g -ge 20 && $g -le 50 ]] && sed "s%--target-peers [0-9]*%--target-peers $g%" ~/$ethb.save > /etc/systemd/system/$ethb.service
+          nn=$(num $(($(grep target-peers ~/$ethb.save|sed 's%.*target-peers \([0-9]*\).*%\1%')+$1)))
+          [[ $nn -ge 20 && $nn -le 50 ]] && sed "s%--target-peers [0-9]*%--target-peers $nn%" ~/$ethb.save > /etc/systemd/system/$ethb.service
         fi
-        bk
-        if [[ $2 || $ok != 'OK' ]]; then
-          echo -e "RSTI $m" >> $p2
+        if [[ $ok != 'OK' ]]; then
+          bko;echo -e "RSTI $m" >> $p2
           resolvectl query smtp.gmail.com 2>/dev/null 1>&2
           [[ $2 = vcreset ]] && { echo $H|sudo -S systemctl stop $ethv 2>/dev/null; }
           echo $H|sudo -S systemctl stop $ethb    2>/dev/null
           echo $H|sudo -S systemctl daemon-reload 2>/dev/null
-          n=400
           if [[ $2 = reboot ]]; then
-            rm -f /home/eth/beacon.restart.inicio
             echo $H|sudo -S reboot 2>/dev/null
           else
             echo $H|sudo -S systemctl start $ethb 2>/dev/null
@@ -458,7 +449,7 @@ function ssp {
 [[ $1 = blf ]] && { bk;echo -e "BEAC $m" >> $p2; }
 [[ $1 = bmf ]] && { bm;echo -e "BEAC $m" >> $p3; }
 [[ $1 = bnf ]] && { bm;echo -e "BEAC $s" >> $p7; }
-[[ $1 = bmc ]] && { bm;echo -e "BEAC $m" >> $p3;[[ $b5 -ne 0 ]] && { sleep 3m;brs $b5 bnreset; } }
+[[ $1 = bmc ]] && { bm;echo -e "BEAC $m" >> $p3;[[ $b5 -ne 0 ]] && { sleep 3m;brs $b5 pereset; } }
 [[ $1 = gh  ]] && { [[ -f $p5 ]] && { tail -n ${2:-$hors} $p5;gk;echo -e "GETH $m\n";sst GETH "$(systemctl status $ethg)";csh;psh;esh; } }
 [[ $1 = bh  ]] && { [[ -f $p2 ]] && { bh $2;[[ $2 ]] || { csh;psh;esh; } } }
 [[ $1 = bhr ]] && { [[ -f $p2 ]] && { bhr; } }
