cleanup

diff --git a/t6 b/t6
--- a/t6
+++ b/t6
@@ -13,25 +13,25 @@ function nu6 { if [[ $@        ]];then echo $(nu3 $(nu2 $@)/$(echo $@|wc -w) 5 1
 function nu7 { if [[ $1 -ne 0  ]];then echo $1                                                     ;else echo 1;fi; }                                         # get safe denominator
 function nu8 { nu2 $(echo "$l1"|cut -f$1); }                                                                                                                  # get sum specific list of numbers
 function nu9 { echo $1|sed 's%node\([0-9]*\):%\1%'; }                                                                                                         # get peers from node tag
-function cex { echo -e "${i}${1^^}${f}";echo $H|sudo -S $1                      2>/dev/null     ; }                                                           # superuser-command (visible)
-function sex {                          echo $H|sudo -S $1                      2>/dev/null 1>&2; }                                                           # superuser-command (silent)
-function dmr { sex "$sctl daemon-reload"                 ; }                                                                                                  # daemon-reload
-function jsh { cex "journalctl --no-hostname --no-full -f $1"; }                                                                                              # my journal   format
-function dts { date '+%Y-%m-%d %H:%M'; }                                                                                                                      # my logs date format
-function fs2 { echo $1|egrep '^[0-9]+$'       ; }                                                                                                             # integer test
-function fs3 { echo $1|egrep '^[0-9]+:[0-9]+$'; }                                                                                                             # hh:mm   test
-function fs4 { echo $H|sudo -S grep "${3:-lighthouse}.*$1"  $p4 2>/dev/null|if [[ ${2:-0} -le 0 ]];then cat;else tail -n${2:-0};fi; }                         # get tail     syslog lines
-function fs5 { echo $H|sudo -S grep -v 'geth\[\|lighthouse' $p4 2>/dev/null; }                                                                                # get sys      syslog lines
-function fs6 { echo $H|sudo -S grep -i 'geth\[\|lighthouse' $p4 2>/dev/null; }                                                                                # get eth      syslog lines
-function fs7 { echo $H|sudo -S grep    "$1"                 $p4 2>/dev/null; }                                                                                # get specific syslog lines
-function sst { echo "$1 $(printf '%6s' $(rd1 $2 Memory:)) $(dts) status: $(rd1 $2)"; }                                                                        # GETH/BEAC/VALI status
-function dnn { echo "$1 $2 $(printf 'node%02i:' $3) $(printf '%2i' $4)"            ; }                                                                        # date/nodes info
+function fs0 { echo $1|egrep '^[0-9]+$'       ; }                                                                                                             # integer test
+function fs1 { echo $1|egrep '^[0-9]+:[0-9]+$'; }                                                                                                             # hh:mm   test
+function fs2 { echo $H|sudo -S grep -i 'geth\[\|lighthouse'   $p4 2>/dev/null; }                                                                              # get eth      syslog lines
+function fs3 { echo $H|sudo -S grep -v 'geth\[\|lighthouse'   $p4 2>/dev/null; }                                                                              # get sys      syslog lines
+function fs4 { echo $H|sudo -S grep    "${3:-lighthouse}.*$1" $p4 2>/dev/null|if [[ ${2:-0} -le 0 ]];then cat;else tail -n${2:-0};fi; }                       # get tail     syslog lines
+function fs5 { echo $H|sudo -S grep    "$1"                   $p4 2>/dev/null; }                                                                              # get specific syslog lines
 function rd0 { $sctl status $1 2>/dev/null|grep "${2:-inactive\|failed}"                                   ; }                                                # service status word test
 function rd1 { $sctl status $1 2>/dev/null|grep "${2:-Active:}"|sed "s%.*${2:-Active:} *\(${3:-.}*\).*%\1%"; }                                                # service status word with data extraction
 function rd2 { cp $p8/$1.service $p0/$1.sav;sed "s%peers *[0-9]*%peers $2%" $p0/$1.sav > $p8/$1.service; }                                                    # change service configuration file
 function rd3 { resolvectl query smtp.gmail.com 2>/dev/null 1>&2;sex "$sctl stop $1";dmr; }                                                                    # DNS force smpt stop/load service
 function rd4 { local n=$(($2+$3));[[ $2 -ne 0 && $n -ge $4 && $n -le $5 ]] && rd2 $1 $n;rd3 $1; }                                                             # change/stop/load service process
 function rd5 { cex "$sctl stop $dnsd";sex "$sctl stop systemd-resolved";cex "$sctl start $dnsd";sex "$sctl start systemd-resolved"; }                         # DNS stop/start
+function cex { echo -e "${i}${1^^}${f}";echo $H|sudo -S $1                      2>/dev/null     ; }                                                           # superuser-command (visible)
+function sex {                          echo $H|sudo -S $1                      2>/dev/null 1>&2; }                                                           # superuser-command (silent)
+function dmr { sex "$sctl daemon-reload"                     ; }                                                                                              # daemon-reload
+function jsh { cex "journalctl --no-hostname --no-full -f $1"; }                                                                                              # my journal   format
+function dts { date '+%Y-%m-%d %H:%M'; }                                                                                                                      # my logs date format
+function sst { echo "$1 $(printf '%6s' $(rd1 $2 Memory:)) $(dts) status: $(rd1 $2)"; }                                                                        # GETH/BEAC/VALI status
+function dnn { echo "$1 $2 $(printf 'node%02i:' $3) $(printf '%2i' $4)"            ; }                                                                        # date/nodes info
 # geth control commands
 function gv  { nu0 $(rd1 $ethg maxpeers [0-9])                                        ; }                                                                     # get configured peers
 function gq  { nu0 $(geth attach "http://$cgth:8545" --exec net.peerCount 2>/dev/null); }                                                                     # get current    peers
@@ -62,7 +62,7 @@ function bl  { if [[ $(rd0 $ethb running) ]];then bl2;dt=$(dts);nn=$(bv);nr=$(bq
 function bl0 { fs4 "attestation(s).*$1"|sed 's%.*validators: *\[\(.*\)\].*%\1%'|wc -w; }                                                                      # get paid activities
 function bl1 {                                                                                                                                                # set restart idx vars
   z1=${1:-$(echo "$l0"|grep 'rocessed block'|wc -l)};z2=${2:-$(echo "$l0"|grep 'block received'|wc -l)}                                                       # set processed/received blocks
-  z3=${3:-$(echo "$l0"|grep -v ' INFO '     |wc -l)};z4=${4:-$(echo "$l0"|grep ' INFO '        |wc -l)}                                                       # set error/info         lines
+  z3=${3:-$(echo "$l0"|grep -v ' INFO '     |wc -l)};z4=${4:-$(echo "$l0"|grep    ' INFO '     |wc -l)}                                                       # set error/info         lines
   z5=${5:-$(bl0 success)};zk=${6:-$(bl0 missing)};zz=${7:-$(bl0 target)};zx=${8:-$(bl0 head)};zw=${9:-$(bl0 had)};ok=${10:-OK}                                # set success/erros      activities
 }
 function bl2 { b0=${1:-$(fs4 'published block'|wc -l)};b1=${2:-$(nu6 $(fs4 delay_ms:|sed 's%.*delay_ms: *\([0-9]*\).*%\1%'))}; }                              # set published blocks/avg delays
@@ -97,20 +97,20 @@ function bnx { if [[ $1 -ge 20 ]];then bnx $(($1-5)) "$2$3${x[$1]}" "$3";else ec
 function bnw { if [[ $1 -ge 20 ]];then bnw $(($1-5)) "$2$3${w[$1]}" "$3";else echo "$2";fi; }                                                                 # sum recursively delay         err array
 function bnc { if [[ $1 -ge 20 ]];then bnc $(($1-5)) "$2$3${c[$1]}" "$3";else echo "$2";fi; }                                                                 # sum recursively               cnt array
 function bo0 {                                                                                                                                                # homologous lines/position
-  b2=0;[[ ! -f $p2 ]] && return;local t=00:00;[[ $(fs2 $1) ]] && b2=$1;[[ $(fs2 $2) ]] && b2=$2;[[ $(fs3 $1) ]] && t=$1;[[ $(fs3 $2) ]] && t=$2               # forced position/time
-  local l=$(grep BEAC $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\).*%\1\t\2%')                                                           # last date/time in beacon log
-  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2);l2=$(cat $p2|bo2 $t);[[ $b2 -eq 0 ]] && b2=$(bo3 $d)                                # set homologous lines/position
+  b2=0;[[ ! -f $p2 ]] && return;local t=00:00;[[ $(fs0 $1) ]] && b2=$1;[[ $(fs0 $2) ]] && b2=$2;[[ $(fs1 $1) ]] && t=$1;[[ $(fs1 $2) ]] && t=$2               # forced position/time
+  local l=$(bo2 . $p2|tail -n1|sed 's%.* \([0-9]*-[0-9]*-[0-9]*\) \([0-9]*:[0-9]*\).*%\1\t\2%')                                                               # last date/time in beacon log
+  local d=$(echo "$l"|cut -f1);[[ $t = 00:00 ]] && t=$(echo "$l"|cut -f2);l2=$(bo2 $t $p2);[[ $b2 -eq 0 ]] && b2=$(bo3 $d)                                    # set homologous lines/position
   local n=0;while [[ ${b2:=0} -eq 0 && $n -lt 50 ]];do ((n+=1));d=$(date -d "$n days ago $t" '+%Y-%m-%d');b2=$(bo3 $d);done                                   # search past homologous info (max 50 days)
 }
 function bo1 {                                                                                                                                                # homologous report
   [[ ! -f $p2 ]] && return;local g=${b2:-0};local d=${b2:-0}                                                                                                  # init head/tail lines
-  if [[ $(fs2 $1) ]];then g=$1;else if [[ $g -lt 5 && $(bo4) -ge 5 ]];then d=5;g=5;fi;fi                                                                      # ajust head lines
-  if [[ $(fs2 $1) ]];then d=$1;else if [[ $d -gt $hors             ]];then d=$hors;fi;fi;bo6|head -n$g|tail -n$d                                              # ajust tail lines & homologous report
+  if [[ $(fs0 $1) ]];then g=$1;else if [[ $g -lt 5 && $(bo4) -ge 5 ]];then d=5;g=5;fi;fi                                                                      # ajust head lines
+  if [[ $(fs0 $1) ]];then d=$1;else if [[ $d -gt $hors             ]];then d=$hors;fi;fi;bo6|head -n$g|tail -n$d                                              # ajust tail lines & homologous report
 }
-function bo2 { grep "BEAC.*${1:-23:58}"  ; }                                                                                                                  # get homologous beacon lines
-function bo3 { bo6|grep -n $1|cut -d: -f1; }                                                                                                                  # get homologous beacon lines position
-function bo4 { echo "$l2"|wc -l          ; }                                                                                                                  # get homologous beacon lines count
-function bo6 { echo "$l2"|sort -k10.1n   ; }                                                                                                                  # get homologous beacon lines sorted
+function bo2 { cat $2|grep "BEAC.*${1:-23:58}"; }                                                                                                             # get homologous beacon lines
+function bo3 { bo6|grep -n $1|cut -d: -f1     ; }                                                                                                             # get homologous beacon lines position
+function bo4 { echo "$l2"|wc -l               ; }                                                                                                             # get homologous beacon lines count
+function bo6 { echo "$l2"|sort -k10.1n        ; }                                                                                                             # get homologous beacon lines sorted
 function bh  {                                                                                                                                                # historic report
   [[ ! -f $p2 ]] && return;tail -n${1:-$hors} $p2;[[ $1 ]] && return;bo0;echo -e "BO$(printf '%5i' $(bo4)) $(printf '%3i' $b2)";bo1                           # beacon/homologous report
   bl;echo -e "BL$(printf '%9i' $(cat $p2 2>/dev/null|wc -l))\nBEAC$m";bm;echo -e "BM$(printf '%5i' $(cat $p3 2>/dev/null|wc -l))\nBEAC$m"                     # beacon/medias report
@@ -156,24 +156,24 @@ function nsh {
 }
 function cpe {                                                                                                                                                # system status
   local e='NO';[[ $(timedatectl|grep synchronized:|sed 's%.*synchronized: \([a-z]*\).*%\1%') = yes ]] && e='OK'                                               # clock info
-  echo "CLCK $e $(printf '%3i' $(fs7 'check system clock'|wc -l)) $(dts) status: $(rd1 systemd-timesyncd)"
+  echo "CLCK $e $(printf '%3i' $(fs5 'check system clock'|wc -l)) $(dts) status: $(rd1 systemd-timesyncd)"
   [[ $1 = c ]] && return;local l=0;local n=0;local v=0                                                                                                        # cpu info
-  local e=$(fs7 'ture/speed normal'|tail -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
-  local d=$(fs7 'e above threshold'|head -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
+  local e=$(fs5 'ture/speed normal'|tail -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
+  local d=$(fs5 'e above threshold'|head -n1|sed 's%.* \([0-9]*:[0-9]*:[0-9]*\).*%\1%')
   for v in $(sensors 2>/dev/null|grep 'Package\|Core'|sed 's%.*: *\([-+][0-9][0-9]*\.[0-9]*\).*%\1%');do n=$((n+1));l=$(nu1 $l$v 1);done
   [[ $e ]] && e="normal: $e";[[ $d ]] && d="throttled: $d";echo "TEMP $(nu3 $l/$(nu7 $n) 1 1 %5.1fC) $(dts) $d $e"
-  [[ $1 = p ]] && return;local l=$(fs5|grep -i 'error' |wc -l);local n=$(fs6|grep -v ' INFO '|wc -l)                                                          # sys/eth error info
-  local e=$(fs5|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'|cut -c1-53)
-  local d=$(fs6|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
+  [[ $1 = p ]] && return;local l=$(fs3|grep -i 'error' |wc -l);local n=$(fs2|grep -v ' INFO '|wc -l)                                                          # sys/eth error info
+  local e=$(fs3|grep -i 'error' |tail -n1|sed 's%.*hrv-zotac[0-9] *\(.*\)%\1%;s%:%%g;s%  *% %g'                                |cut -c1-53)
+  local d=$(fs2|grep -v ' INFO '|tail -n1|sed 's%.*[0-9]*:[0-9]*:[0-9]*\.[0-9][0-9][0-9]]* *\(.*\)%\1%;s%:%%g;s%:%%g;s%  *% %g'|cut -c1-53)
   m="ERRO $(printf '%2i' $l) $(printf '%3i' $n) $(dts)";[[ $l -gt 0 ]] && m="$m sys: $e";[[ $n -gt 0 ]] && m="$m eth2: $d";echo "$m"
 }
 function blo {
-  #    0  1   2          3     4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18     19  20  21   22   23   24         25   26
-  # BEAC OK   0 2021-11-22 17:15 node20: 32 reward_penalty: 224 3.54 attestation_block: 2950 2280 0 erros: 2 14 131 29      0 537   0   14 3586 1260     delay: 1000
+  #    0  1   2          3     4       5  6               7   8    9                 10   11  12 13    14 15 16  17 18 19  20  21  22   23   24     25  26
+  # BEAC OK   0 2022-01-03 19:58 node50: 55 reward_penalty: 257 2.23 attestation_block: 3384 1310 0 erros: 0  7  93 17  0 581   0   8 3592  720 delay: 428
   m=" $ok $(printf '%3i' $(bu)) $(dnn $dt $nn $nr) reward_penalty: $(nu3 "($z5*$ratt+$b0*$rblk)*$rate/$decp" 0 1 %3i) $(printf '%4.2f' $(nu4 $zk $zz $zx $zw 1))"
   m="$m attestation_block: $(printf '%4i' $z5) $(printf '%4i' $(bz)) $(printf '%1i' $b0) erros: $(printf '%1i' $zk) $(printf '%2i' $zz) $(printf '%3i' $zx)"
-  m="$m $(printf '%2i' $zw) $(printf '%6i' $z1) $(printf '%3i' $z2) $(printf '%3i' $(bw)) $(printf '%4i' $z3) $(printf '%4i' $z4) $(printf '%4i' $(bf))    "
-  m="$m delay: $(printf '%4i' $b1)"
+  m="$m $(printf '%2i' $zw) $(printf '%2i' $z1) $(printf '%3i' $z2) $(printf '%3i' $(bw)) $(printf '%2i' $z3) $(printf '%4i' $z4) $(printf '%4i' $(bf))"
+  m="$m delay: $(printf '%3i' $b1)"
 }
 function bmo {
   #    0  1   2          3     4       5  6    7    8    9   10   11   12   13   14          15   16                  17 18 19
@@ -315,8 +315,8 @@ function ssp {
 # lista servicos & portas
 [[ $1 = lp  ]] && { netstat -tulpn; }
 # outros journal system/lighthouse
-[[ $1 = el  ]] && { fs6|if [[ $2 ]];then grep -i "[a-z]* [0-9]* $2";else grep -v ' INFO ';fi; }
-[[ $1 = sl  ]] && { fs5|if [[ $2 ]];then grep -i "[a-z]* [0-9]* $2";else grep -i 'error' ;fi; }
+[[ $1 = el  ]] && { fs2|if [[ $2 ]];then grep -i "[a-z]* [0-9]* $2";else grep -v ' INFO ';fi; }
+[[ $1 = sl  ]] && { fs3|if [[ $2 ]];then grep -i "[a-z]* [0-9]* $2";else grep -i 'error' ;fi; }
 [[ $1 = ws  ]] && { cex 'ufw status numbered'; }
 [[ $1 = wa  ]] && { wa; }
 [[ $1 = wpr ]] && { cex 'ufw disable'; }
